import { useState, type ReactNode } from 'react'
import { demoDemand, demoDfd, demoEtp, demoMatrixRisks, demoPriceReferences, demoRequirements, demoTr } from '../procurement/demoProcess'

const titles = ['Problema da Prefeitura','Demanda','DFD','ETP','Riscos','Pesquisa de Preços','Termo de Referência','Revisão Inteligente','Copiloto','Resultado']
const money = (value:number) => value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const referenceValues = demoPriceReferences.filter(ref=>ref.itemId===1).map(ref=>Number(ref.unitValue)).sort((a,b)=>a-b)
const mean = referenceValues.reduce((sum,value)=>sum+value,0)/referenceValues.length
const median = referenceValues[1]

function Highlight({label,value,wide=false}:{label:string;value:ReactNode;wide?:boolean}){return <div className={`demo-highlight ${wide?'wide':''}`}><small>{label}</small><strong>{value}</strong></div>}
function Message({children}:{children:ReactNode}){return <div className="demo-value-message">{children}</div>}

export default function DemoMode({onExit}:{onExit:()=>void}){
 const [step,setStep]=useState(0)
 const next=()=>setStep(Math.min(9,step+1));const previous=()=>setStep(Math.max(0,step-1))
 const content:ReactNode[]=[
  <div className="demo-story problem-story"><span className="demo-story-icon">01</span><h2>Uma secretaria identifica uma necessidade.</h2><blockquote>“O atendimento ao cidadão depende de processos manuais, formulários e acompanhamento disperso.”</blockquote><Message>O GOV TOTAL transforma essa necessidade em um processo estruturado de contratação.</Message></div>,
  <><div className="demo-showcase-grid"><Highlight label="Objeto" value={demoDemand.object} wide/><Highlight label="Secretaria" value={`${demoDemand.secretariat} · DEMO`}/><Highlight label="Problema" value={demoDemand.problem}/><Highlight label="Resultado esperado" value={demoDemand.result}/></div><Message>Os dados são informados uma única vez e reaproveitados nas próximas etapas.</Message></>,
  <><div className="demo-origin"><span>DEMANDA</span><i>→</i><strong>DFD criado a partir da Demanda</strong></div><div className="demo-showcase-grid inherited-grid"><Highlight label="Herdado · Objeto" value={demoDemand.object}/><Highlight label="Herdado · Necessidade" value={demoDemand.need}/><Highlight label="Herdado · Responsável" value={demoDemand.owner}/><Highlight label="Complemento do DFD" value={demoDfd.justification}/></div><Message>Menos redigitação e menos risco de inconsistência.</Message></>,
  <><div className="demo-showcase-grid"><Highlight label="Alternativas analisadas" value="Desenvolvimento próprio · SaaS · Solução compartilhada" wide/><Highlight label="Solução escolhida" value={demoEtp.recommended}/><Highlight label="Requisitos" value={demoRequirements.map(item=>item.title).join(' · ')}/><Highlight label="Viabilidade" value={`${demoEtp.viable} · ${demoEtp.conclusion}`}/></div><button className="demo-ai-action">✨ Comparar alternativas <small>SIMULAÇÃO</small></button><Message>O servidor continua decidindo. A tecnologia ajuda a estruturar a análise.</Message></>,
  <><button className="demo-ai-action">✨ Sugerir riscos possíveis <small>SIMULAÇÃO</small></button><div className="demo-risk-list">{[...demoMatrixRisks,{...demoMatrixRisks[0],id:2,title:'DEMO — Baixa adesão',probability:'Média',impact:'Médio',preventive:'Capacitar servidores e orientar cidadãos.'},{...demoMatrixRisks[0],id:3,title:'DEMO — Indisponibilidade',probability:'Baixa',impact:'Alto',preventive:'Definir SLA e canal de contingência.'}].map(r=><article key={r.id}><strong>{r.title}</strong><div><span>Probabilidade <b>{r.probability}</b></span><span>Impacto <b>{r.impact}</b></span></div><p><b>Prevenção:</b> {r.preventive}</p></article>)}</div></>,
  <><div className="demo-reference-list">{demoPriceReferences.filter(ref=>ref.itemId===1).map(ref=><article key={ref.id}><span>Considerada</span><strong>{ref.provider}</strong><b>{money(Number(ref.unitValue))}</b><small>{ref.identifier}</small></article>)}<article className="discarded"><span>Desconsiderada</span><strong>Referência antiga — DEMO</strong><b>{money(98000)}</b><small>Justificativa: preço antigo e condição não comparável.</small></article></div><div className="demo-price-summary"><Highlight label="Média" value={money(mean)}/><Highlight label="Mediana" value={money(median)}/><Highlight label="Valor estimado final" value={money(median)}/></div><Message>Cada preço mantém sua origem e justificativa.</Message></>,
  <><div className="demo-origin"><span>DFD + ETP + RISCOS + PREÇOS</span><i>→</i><strong>TR estruturado</strong></div><div className="demo-showcase-grid"><Highlight label="Objeto" value={demoDemand.object}/><Highlight label="Requisitos" value={`${demoRequirements.length} requisitos conectados`}/><Highlight label="Execução" value={demoTr.deliveryDeadline}/><Highlight label="Fiscalização" value={demoTr.monitoring}/><Highlight label="Valor estimado" value={money(median)}/></div><button className="demo-ai-action">✨ Preparar esta seção <small>SIMULAÇÃO</small></button><Message>Grande parte do TR já está estruturada com dados das etapas anteriores.</Message></>,
  <><div className="demo-review-list">{[['Crítico','Risco alto sem contingência'],['Importante','SLA ainda não definido'],['Atenção','Poucas referências de preço'],['Importante','Campo essencial ainda vazio']].map(([severity,text])=><article key={text}><span>{severity}</span><strong>{text}</strong><button>Corrigir</button></article>)}</div><Message>O sistema revisa o processo antes do encaminhamento.</Message></>,
  <><div className="demo-copilot-capabilities">{['Ajudar a escrever','Revisar','Explicar','Comparar','Sugerir riscos','Preparar seções'].map(item=><div key={item}><span>✨</span><strong>{item}</strong><small>Sugestão DEMO</small></div>)}</div><div className="demo-control-message"><strong>A IA auxilia.</strong><span>O servidor mantém controle e responsabilidade.</span><small>Conteúdo sugerido pelo GOV TOTAL. Revise antes de utilizar.</small></div></>,
  <><div className="demo-result"><span>DEMO</span><h2>Da necessidade ao Termo de Referência em um único fluxo.</h2><p>{demoDemand.object}</p><div>{['7 etapas estruturadas','Documentos conectados','Pesquisa rastreável','Revisão automática','Assistência por IA','Histórico do processo'].map(item=><strong key={item}>✓ {item}</strong>)}</div></div><div className="demo-cta">Processo pronto para revisão e aprovação.</div></>,
 ]
 return <div className="commercial-demo"><header><div><span>MODO DEMONSTRAÇÃO · GOV TOTAL</span><h1>{titles[step]}</h1><p>Processo: Contratação de plataforma digital de atendimento ao cidadão · DEMO</p></div><div className="demo-progress"><strong>Passo {step+1} de 10</strong><i><b style={{width:`${(step+1)*10}%`}}/></i></div></header><main>{content[step]}</main><footer><button className="secondary" disabled={step===0} onClick={previous}>← Anterior</button><div>{titles.map((title,index)=><button aria-label={`Ir para ${title}`} className={index===step?'active':''} onClick={()=>setStep(index)} key={title}/>)}</div><button className="demo-exit" onClick={onExit}>Sair da demonstração</button>{step<9?<button className="primary" onClick={next}>Próximo →</button>:<button className="primary" onClick={onExit}>Concluir demonstração</button>}</footer></div>
}
