import { deodapolisRequirements } from './deodapolisRequirements.ts'
export type ProviderAnswer='ATENDE'|'NÃO ATENDE'|'PARCIAL'|'NÃO INFORMADO'
export type EmailResponsibility='FORNECEDOR_EMAIL'|'GOV_TOTAL'|'INFRAESTRUTURA'|'COMPARTILHADO'
export type EmailCategory='CAIXA POSTAL'|'WEBMAIL'|'SMTP'|'IMAP'|'POP3'|'TLS/SSL'|'ANTISPAM'|'ANTIVÍRUS'|'BACKUP'|'ADMINISTRAÇÃO'|'DOMÍNIO'|'SEGURANÇA'|'DISPONIBILIDADE'|'SUPORTE'|'MIGRAÇÃO'|'OUTROS'
export type ProviderEvaluation={requirement:string;answer:ProviderAnswer;evidence:string;note:string;risk:string}
export type EmailProvider={id:string;name:string;monthlyPrice:string;annualPrice:string;implementationDays:string;evaluations:ProviderEvaluation[]}
export const emailRequirements=deodapolisRequirements.filter(item=>item.group==='Correio Eletrônico')
const shared=new Set(['4.4.1','4.4.18','4.4.21','4.4.34'])
const categories:Record<string,EmailCategory>={'4.4.1':'DOMÍNIO','4.4.2':'WEBMAIL','4.4.3':'WEBMAIL','4.4.4':'CAIXA POSTAL','4.4.5':'CAIXA POSTAL','4.4.6':'ADMINISTRAÇÃO','4.4.7':'ADMINISTRAÇÃO','4.4.8':'ADMINISTRAÇÃO','4.4.9':'WEBMAIL','4.4.10':'WEBMAIL','4.4.11':'WEBMAIL','4.4.12':'WEBMAIL','4.4.13':'WEBMAIL','4.4.14':'WEBMAIL','4.4.15':'WEBMAIL','4.4.16':'ANTISPAM','4.4.18':'TLS/SSL','4.4.19':'IMAP','4.4.21':'MIGRAÇÃO','4.4.22':'ADMINISTRAÇÃO','4.4.23':'ADMINISTRAÇÃO','4.4.24':'ADMINISTRAÇÃO','4.4.25':'SEGURANÇA','4.4.27':'ADMINISTRAÇÃO','4.4.29':'SEGURANÇA','4.4.30':'ADMINISTRAÇÃO','4.4.31':'BACKUP','4.4.33':'SEGURANÇA','4.4.34':'MIGRAÇÃO'}
export const requirementMetadata=(number:string)=>({category:categories[number]??'OUTROS' as EmailCategory,responsibility:shared.has(number)?'COMPARTILHADO' as const:'FORNECEDOR_EMAIL' as const,evidence:`Demonstração ao vivo e documentação técnica para ${number}.`,risk:emailRequirements.find(item=>item.number===number)?.kind==='OBRIGATÓRIO'?'Eliminatório para homologação técnica da POC.':'Lacuna funcional ou operacional a avaliar.'})
export const emailRequirementCounts=()=>({total:emailRequirements.length,required:emailRequirements.filter(item=>item.kind==='OBRIGATÓRIO').length,additional:emailRequirements.filter(item=>item.kind==='COMPLEMENTAR').length})
export const providerScore=(provider:EmailProvider)=>{const confirmed=new Set(provider.evaluations.filter(item=>item.answer==='ATENDE'&&item.evidence.trim()).map(item=>item.requirement));const required=emailRequirements.filter(item=>item.kind==='OBRIGATÓRIO');const additional=emailRequirements.filter(item=>item.kind==='COMPLEMENTAR');const requiredMet=required.filter(item=>confirmed.has(item.number)).length;const additionalMet=additional.filter(item=>confirmed.has(item.number)).length;return{requiredMet,requiredTotal:required.length,additionalMet,additionalTotal:additional.length,verdict:requiredMet===required.length?'APTO TECNICAMENTE PARA TESTE' as const:'NÃO APTO' as const}}
export const blankProvider=(index:number):EmailProvider=>({id:`provider-${index}`,name:`Fornecedor ${String.fromCharCode(64+index)}`,monthlyPrice:'',annualPrice:'',implementationDays:'',evaluations:emailRequirements.map(item=>({requirement:item.number,answer:'NÃO INFORMADO',evidence:'',note:'',risk:requirementMetadata(item.number).risk}))})
