import type { PortalState } from './types'

export const deodapolisPocConfig={municipality:'Deodápolis',state:'MS',environment:'AMBIENTE DEMONSTRATIVO / POC'}
export const initialPortalState:PortalState={
 news:[
  {id:1,title:'Prefeitura amplia atendimento digital ao cidadão — DEMO',subtitle:'Novo canal demonstrativo aproxima serviços municipais da população.',content:'Conteúdo fictício para a POC. A iniciativa demonstra como notícias e serviços podem ser publicados de forma simples e acessível.',department:'Administração',author:'Equipe POC',cover:'Capa institucional simulada',date:'2026-08-23',status:'Publicado',slug:'prefeitura-amplia-atendimento-digital-demo'},
  {id:2,title:'Secretaria de Administração divulga novo horário — DEMO',subtitle:'Atendimento demonstrativo passa a ter horário ampliado.',content:'Notícia fictícia destinada exclusivamente à validação do portal.',department:'Administração',author:'Equipe POC',cover:'Capa simulada',date:'2026-08-22',status:'Publicado',slug:'novo-horario-administracao-demo'},
  {id:3,title:'Agenda municipal recebe novos eventos — DEMO',subtitle:'Programação está em preparação.',content:'Conteúdo agendado para demonstrar o fluxo editorial.',department:'Cultura',author:'Equipe POC',cover:'Capa simulada',date:'2026-08-30',status:'Agendado',slug:'agenda-municipal-demo'},
 ],
 pages:[{id:1,title:'Prefeitura',slug:'prefeitura',content:'Informações institucionais demonstrativas da Prefeitura.',status:'Publicado'},{id:2,title:'Município',slug:'municipio',content:'História e dados municipais em conteúdo DEMO.',status:'Publicado'},{id:3,title:'Contato',slug:'contato',content:'Canais de atendimento demonstrativos.',status:'Publicado'}],
 documents:[{id:1,title:'Edital demonstrativo 001/2026',slug:'edital-demonstrativo-001-2026',category:'Editais',description:'Arquivo fictício para validação da consulta.',date:'2026-08-20',file:'/demo-documento.txt',status:'Publicado'},{id:2,title:'Relatório de atendimento — DEMO',slug:'relatorio-atendimento-demo',category:'Relatórios',description:'Relatório exclusivamente demonstrativo.',date:'2026-07-15',file:'/demo-documento.txt',status:'Publicado'}],
 legislation:[{id:1,type:'Lei',number:'1001',year:'2026',summary:'Institui programa demonstrativo de atendimento digital.',date:'2026-08-10',content:'Texto legal fictício para POC.',status:'Publicado'},{id:2,type:'Decreto',number:'205',year:'2026',summary:'Regulamenta horário demonstrativo de atendimento.',date:'2026-07-18',content:'Texto fictício.',status:'Publicado'}],
 departments:[{id:1,name:'Administração',head:'Mariana Costa — DEMO',description:'Gestão administrativa e atendimento ao cidadão.',phone:'(00) 0000-1001',email:'administracao@demo.gov.br',address:'Paço Municipal — DEMO',hours:'7h às 13h'},{id:2,name:'Educação',head:'Paulo Mendes — DEMO',description:'Políticas educacionais e rede municipal.',phone:'(00) 0000-1002',email:'educacao@demo.gov.br',address:'Centro Administrativo — DEMO',hours:'7h às 13h'},{id:3,name:'Saúde',head:'Ana Oliveira — DEMO',description:'Atenção básica e serviços municipais de saúde.',phone:'(00) 0000-1003',email:'saude@demo.gov.br',address:'Secretaria de Saúde — DEMO',hours:'7h às 17h'}],
 banners:[{id:1,title:'Atendimento digital — DEMO',image:'Banner institucional simulado',link:'#servicos',order:1,active:true}],
 agenda:[{id:1,event:'Audiência pública demonstrativa',date:'2026-09-10',time:'19:00',place:'Câmara Municipal — DEMO',description:'Evento fictício para teste da agenda.',status:'Publicado'}],
 quickLinks:[['Portal da Transparência','transparency'],['Diário Oficial','gazette'],['e-SIC','esic'],['Ouvidoria','ombudsman'],['Licitações','documents'],['Contratos','contracts'],['Carta de Serviços','services']].map(([label,target],index)=>({id:index+1,label,target,active:true,external:false})),
 externalLinks:[{id:1,label:'Sistema externo DEMO A',url:'https://example.com/sistema-a'},{id:2,label:'Sistema externo DEMO B',url:'https://example.com/sistema-b'}],
 menuOrder:['Início','Prefeitura','Secretarias','Notícias','Legislação','Documentos','Diário Oficial','Transparência','e-SIC','Contato'],
}
