import { useState } from 'react'
import { deodapolisPocConfig } from './demoData'
import { contentPath, findBySlug, type News, type PortalState } from './types'
import GazettePublicArchive from '../official-gazette/GazettePublicArchive'
import type { GazetteState } from '../official-gazette/types'
import './portal.css'

type Section='home'|'pages'|'news'|'legislation'|'documents'|'departments'|'gazette'|'transparency'|'esic'|'ombudsman'|'contracts'|'services'|'contact'
const targets:Record<string,Section>={'Início':'home','Prefeitura':'pages','Secretarias':'departments','Notícias':'news','Legislação':'legislation','Documentos':'documents','Diário Oficial':'gazette','Transparência':'transparency','e-SIC':'esic','Contato':'contact'}
export default function PortalPublic({data,gazette,onBack}:{data:PortalState;gazette:GazetteState;onBack:()=>void}){
 const [section,setSection]=useState<Section>(()=>location.pathname.startsWith('/diario/')?'gazette':'home');const [font,setFont]=useState(100);const [contrast,setContrast]=useState(false);const [query,setQuery]=useState('');const [selectedNews,_setSelectedNews]=useState<News|null>(null);const [lawType,setLawType]=useState('');const [lawNumber,setLawNumber]=useState('');const [lawYear,setLawYear]=useState('');const [docCategory,setDocCategory]=useState('');const [docYear,setDocYear]=useState('')
 const setSelectedNews=(news:News|null)=>{_setSelectedNews(news);if(news)history.pushState({},'',contentPath('noticias',news.slug))};const go=(target:string)=>{setSection((targets[target]??target) as Section);_setSelectedNews(null);window.scrollTo({top:0})};const published=data.news.filter(x=>x.status==='Publicado');const contains=(...values:string[])=>values.join(' ').toLowerCase().includes(query.toLowerCase());const [,directType,directSlug]=location.pathname.split('/');const directNews=directType==='noticias'?findBySlug(data.news,directSlug):undefined;const directPage=directType==='paginas'?findBySlug(data.pages,directSlug):undefined;const directDocument=directType==='documentos'?findBySlug(data.documents,directSlug):undefined
 if(directNews||directPage||directDocument){const title=directNews?.title??directPage?.title??directDocument?.title??'';const content=directNews?.content??directPage?.content??directDocument?.description??'';return <div className="public-portal"><div className="poc-ribbon">AMBIENTE DEMONSTRATIVO / POC</div><main className="public-detail"><a href="/">← Voltar ao portal</a><span>URL PERMANENTE · DEMO</span><h1>{title}</h1><p>{content}</p>{directDocument&&<a className="primary" href={directDocument.file} download>Download do arquivo DEMO</a>}<code>{location.pathname}</code></main></div>}
 return <div className={`public-portal ${contrast?'public-high-contrast':''}`} style={{fontSize:`${font}%`}}><a className="skip-link" href="#conteudo-publico">Ir para o conteúdo</a><div className="poc-ribbon">{deodapolisPocConfig.environment} · conteúdo fictício</div><header className="public-header"><div className="public-accessibility" role="region" aria-label="Painel de acessibilidade"><span>Acessibilidade</span><button onClick={()=>setFont(Math.max(90,font-10))} aria-label="Diminuir fonte">A−</button><button onClick={()=>setFont(Math.min(130,font+10))} aria-label="Aumentar fonte">A+</button><button onClick={()=>setFont(100)}>Restaurar fonte</button><button aria-pressed={contrast} onClick={()=>setContrast(!contrast)}>Alto contraste</button><button onClick={onBack}>Voltar ao painel</button></div><div className="public-brand"><div aria-hidden="true">PM</div><span>PREFEITURA MUNICIPAL<strong>{deodapolisPocConfig.municipality}</strong><small>{deodapolisPocConfig.state}</small></span></div><nav aria-label="Menu principal">{data.menuOrder.map(label=><button className={section===targets[label]?'active':''} onClick={()=>go(label)} key={label}>{label}</button>)}</nav></header><main id="conteudo-publico">
 {section==='home'&&<><section className="public-banners" aria-label="Banners institucionais">{data.banners.filter(x=>x.active).sort((a,b)=>a.order-b.order).map(item=><article key={item.id}><span>BANNER DEMO · ORDEM {item.order}</span><strong>{item.title}</strong><small>{item.image}</small></article>)}</section><section className="public-hero"><div><span>PORTAL INSTITUCIONAL · DEMO</span><h1>Informação pública simples e acessível.</h1><p>Serviços, notícias, legislação e documentos em poucos passos.</p><label><span className="sr-only">Busca geral</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="O que você procura?"/><button>Buscar</button></label></div></section><Title title="Acessos rápidos"/><section className="quick-access">{data.quickLinks.filter(x=>x.active).map(item=><button onClick={()=>go(item.target)} key={item.id}><span>↗</span><strong>{item.label}</strong><small>Acesso direto · DEMO</small></button>)}</section><Title title="Últimas notícias"/><section className="public-news-grid">{published.filter(x=>contains(x.title,x.subtitle)).slice(0,3).map(item=><NewsCard item={item} open={()=>setSelectedNews(item)} key={item.id}/>)}</section><Title title="Secretarias"/><section className="public-department-grid">{data.departments.map(item=><button onClick={()=>go('departments')} key={item.id}><strong>{item.name}</strong><span>{item.description}</span><small>Ver informações →</small></button>)}</section><Title title="Sistemas externos"/><section className="latest-publications">{data.externalLinks.map(item=><a className="external-system" href={item.url} target="_blank" rel="noreferrer" key={item.id}><strong>{item.label}</strong><small>Link externo DEMO ↗</small></a>)}</section></>}
 {section==='news'&&!selectedNews&&<List title="Notícias"><Search value={query} set={setQuery}/><div className="public-results">{published.filter(x=>contains(x.title,x.subtitle,x.content)).map(item=><NewsCard item={item} open={()=>setSelectedNews(item)} key={item.id}/>)}</div></List>}
 {section==='pages'&&<List title="Páginas Institucionais"><div className="public-results">{data.pages.filter(x=>x.status==='Publicado').map(page=><article className="public-result" key={page.id}><span>PÁGINA</span><strong>{page.title}</strong><p>{page.content}</p><a href={contentPath('paginas',page.slug)}>Abrir página</a></article>)}</div></List>}
 {selectedNews&&<article className="public-detail"><button onClick={()=>setSelectedNews(null)}>← Voltar</button><span>NOTÍCIA · DEMO</span><h1>{selectedNews.title}</h1><p className="lead">{selectedNews.subtitle}</p><small>URL permanente: /noticias/{selectedNews.slug}</small><div className="public-cover" role="img" aria-label={selectedNews.cover}>{selectedNews.cover}</div><p>{selectedNews.content}</p></article>}
 {section==='legislation'&&<List title="Consulta à legislação"><div className="public-filters"><select aria-label="Espécie" value={lawType} onChange={e=>setLawType(e.target.value)}><option value="">Todas as espécies</option>{['Lei','Decreto','Portaria','Resolução'].map(x=><option key={x}>{x}</option>)}</select><input aria-label="Número" value={lawNumber} onChange={e=>setLawNumber(e.target.value)} placeholder="Número"/><input aria-label="Ano" value={lawYear} onChange={e=>setLawYear(e.target.value)} placeholder="Ano"/><Search value={query} set={setQuery}/></div><div className="public-results">{data.legislation.filter(x=>x.status==='Publicado'&&(!lawType||x.type===lawType)&&(!lawNumber||x.number.includes(lawNumber))&&(!lawYear||x.year===lawYear)&&contains(x.summary,x.content)).map(x=><Result tag={`${x.type} ${x.number}/${x.year}`} title={x.summary} meta={`${x.date} · DEMO`} key={x.id}/>)}</div></List>}
 {section==='documents'&&<List title="Consulta de documentos"><div className="public-filters"><select aria-label="Categoria" value={docCategory} onChange={e=>setDocCategory(e.target.value)}><option value="">Todas as categorias</option>{['Editais','Decretos','Portarias','Relatórios','Outros'].map(x=><option key={x}>{x}</option>)}</select><input aria-label="Ano" value={docYear} onChange={e=>setDocYear(e.target.value)} placeholder="Ano"/><Search value={query} set={setQuery}/></div><div className="public-results">{data.documents.filter(x=>x.status==='Publicado'&&(!docCategory||x.category===docCategory)&&(!docYear||x.date.startsWith(docYear))&&contains(x.title,x.description)).map(x=><article className="public-result" key={x.id}><span>{x.category}</span><strong>{x.title}</strong><p>{x.description}</p><small>URL permanente: /documentos/{x.slug}</small><a href={contentPath('documentos',x.slug??'')} >Abrir documento</a><a href={x.file} download>Baixar arquivo DEMO</a></article>)}</div></List>}
 {section==='departments'&&<List title="Secretarias Municipais"><Search value={query} set={setQuery}/><div className="public-results">{data.departments.filter(x=>contains(x.name,x.description,x.head)).map(x=><article className="public-result" key={x.id}><span>SECRETARIA</span><strong>{x.name}</strong><p>{x.description}</p><small>{x.head}<br/>{x.phone} · {x.email}<br/>{x.hours}</small></article>)}</div></List>}
 {section==='gazette'&&<GazettePublicArchive state={gazette} onBack={()=>go('home')}/>} 
 {['transparency','esic','ombudsman','contracts','services','contact'].includes(section)&&<section className="public-placeholder"><span>ACESSO DIRETO · DEMO / POC</span><h1>{section==='transparency'?'Portal da Transparência':section==='esic'?'e-SIC':section==='ombudsman'?'Ouvidoria':section==='contracts'?'Contratos':section==='services'?'Carta de Serviços':'Contato'}</h1><p>Acesso realizado diretamente a partir da home pública em uma interação.</p><button onClick={()=>go('home')}>Voltar ao início</button></section>}
 </main><footer className="public-footer"><div><strong>Prefeitura Municipal de Deodápolis</strong><span>Portal demonstrativo para POC.</span></div></footer></div>
}
function Title({title}:{title:string}){return <header className="public-section-title"><h2>{title}</h2></header>}
function List({title,children}:{title:string;children:React.ReactNode}){return <section className="public-list-page"><span>CONSULTA PÚBLICA · DEMO</span><h1>{title}</h1>{children}</section>}
function Search({value,set}:{value:string;set:(value:string)=>void}){return <label><span className="sr-only">Palavra-chave</span><input value={value} onChange={e=>set(e.target.value)} placeholder="Palavra-chave"/></label>}
function NewsCard({item,open}:{item:News;open:()=>void}){return <article className="public-news-card"><div role="img" aria-label={item.cover}>{item.cover}</div><span>{item.department}</span><h3>{item.title}</h3><p>{item.subtitle}</p><button onClick={open}>Ler notícia</button></article>}
function Result({tag,title,meta}:{tag:string;title:string;meta:string}){return <article className="public-result"><span>{tag}</span><strong>{title}</strong><small>{meta}</small></article>}
