import assert from 'node:assert/strict'
import test from 'node:test'
import { blankProvider,emailRequirementCounts,emailRequirements,providerScore } from '../src/features/poc/emailProvider.ts'
test('Correio possui 29 requisitos únicos, sendo 9 obrigatórios e 20 complementares',()=>{assert.deepEqual(emailRequirementCounts(),{total:29,required:9,additional:20});assert.equal(new Set(emailRequirements.map(item=>item.number)).size,29);assert.deepEqual(emailRequirements.filter(item=>item.kind==='OBRIGATÓRIO').map(item=>item.number),['4.4.2','4.4.3','4.4.4','4.4.5','4.4.18','4.4.19','4.4.21','4.4.33','4.4.34']);assert.equal(emailRequirements.some(item=>item.description.includes('Descrição oficial detalhada não fornecida')),false)})
test('fornecedor com 8 de 9 obrigatórios não é apto',()=>{const provider=blankProvider(1);const ids=emailRequirements.filter(item=>item.kind==='OBRIGATÓRIO').slice(0,8).map(item=>item.number);provider.evaluations=provider.evaluations.map(item=>ids.includes(item.requirement)?{...item,answer:'ATENDE',evidence:'Demonstração registrada'}:item);assert.equal(providerScore(provider).requiredMet,8);assert.equal(providerScore(provider).verdict,'NÃO APTO')})
test('fornecedor com 9 de 9 obrigatórios e evidência é apto para teste',()=>{const provider=blankProvider(1);const ids=emailRequirements.filter(item=>item.kind==='OBRIGATÓRIO').map(item=>item.number);provider.evaluations=provider.evaluations.map(item=>ids.includes(item.requirement)?{...item,answer:'ATENDE',evidence:'Demonstração registrada'}:item);assert.equal(providerScore(provider).verdict,'APTO TECNICAMENTE PARA TESTE')})
test('complementares não compensam obrigatório ausente',()=>{const provider=blankProvider(1);provider.evaluations=provider.evaluations.map(item=>({...item,answer:emailRequirements.find(req=>req.number===item.requirement)?.kind==='COMPLEMENTAR'?'ATENDE':'NÃO INFORMADO',evidence:'Evidência'}));assert.equal(providerScore(provider).additionalMet,20);assert.equal(providerScore(provider).verdict,'NÃO APTO')})
test('obrigatório parcial ou não informado nunca homologa',()=>{for(const answer of ['PARCIAL','NÃO INFORMADO']){const provider=blankProvider(1);provider.evaluations=provider.evaluations.map((item,index)=>({...item,answer:emailRequirements.find(req=>req.number===item.requirement)?.kind==='OBRIGATÓRIO'?(index===1?answer:'ATENDE'):'NÃO INFORMADO',evidence:'Evidência'}));assert.equal(providerScore(provider).verdict,'NÃO APTO')}})
test('resposta ATENDE sem evidência não homologa',()=>{const provider=blankProvider(1);provider.evaluations=provider.evaluations.map(item=>({...item,answer:'ATENDE'}));assert.equal(providerScore(provider).requiredMet,0);assert.equal(providerScore(provider).verdict,'NÃO APTO')})
