import assert from 'node:assert/strict'
import test from 'node:test'
import { gazetteDemoState } from '../src/features/official-gazette/demoData.ts'
import { canUseEditionNumber,editionLabel,editionPath,emptyFilters,filterEditions,isEditionMutable,nextEditionNumber,publicEditions,publiclyVisibleActs } from '../src/features/official-gazette/rules.ts'

test('numeração é sequencial e bloqueia duplicidade ou número anterior',()=>{assert.equal(nextEditionNumber(gazetteDemoState.editions,2026),2);assert.equal(canUseEditionNumber(gazetteDemoState.editions,2026,2),true);assert.equal(canUseEditionNumber(gazetteDemoState.editions,2026,1),false);assert.equal(canUseEditionNumber(gazetteDemoState.editions,2026,3),false)})
test('publicação é imutável e minuta não aparece publicamente',()=>{assert.equal(isEditionMutable(gazetteDemoState.editions[0]),false);const publicActs=publiclyVisibleActs(gazetteDemoState.acts);assert.deepEqual(publicActs.map(x=>x.id),['act-published']);assert.equal(publicActs.some(x=>x.status==='MINUTA'),false)})
test('busca alcança conteúdo integral e combina filtros',()=>{const byContent=filterEditions(gazetteDemoState.editions,gazetteDemoState.acts,{...emptyFilters,keyword:'proteção das informações'});assert.equal(byContent.length,1);const combined=filterEditions(gazetteDemoState.editions,gazetteDemoState.acts,{...emptyFilters,keyword:'atendimento digital',sectionId:'executive',actType:'Decreto',from:'2026-08-01',to:'2026-08-31'});assert.equal(combined.length,1);assert.equal(filterEditions(gazetteDemoState.editions,gazetteDemoState.acts,{...emptyFilters,keyword:'reservado enquanto'}).length,0)})
test('URL individual e ordem cronológica são determinísticas',()=>{const edition=gazetteDemoState.editions[0];assert.equal(editionLabel(edition),'000001/2026');assert.equal(editionPath(edition),'/diario/2026/000001');const older={...edition,id:'older',number:2,date:'2026-08-01'};assert.deepEqual(publicEditions([older,edition]).map(x=>x.id),['edition-1','older'])})
