import { useState, type FormEvent, type ReactNode } from 'react'
import Etp, { type Alternative, type EtpData, type Indicator, type Preparation, type Related, type Requirement } from './Etp'
import RiskMatrix, { type RiskItem, type RiskMatrixData } from './RiskMatrix'
import PriceResearch, { type PriceData, type PriceItem, type PriceReference } from './PriceResearch'
import TermReference, { type Milestone, type Sla, type TrData } from './TermReference'
import SmartReview, { runReview, type ReviewContext, type ReviewStage } from './SmartReview'
import Approval from './features/procurement/Approval'
import ProcessOverview, { type OverviewStage } from './features/procurement/ProcessOverview'
import GovCopilot from './components/GovCopilot'
import DemoMode from './features/demo/DemoMode'
import PortalModule from './features/portal/PortalModule'
import PocDashboard from './features/poc/PocDashboard'
import EmailProviderComparator from './features/poc/EmailProviderComparator'
import PocOperatorGuide from './features/poc/PocOperatorGuide'
import './features/poc/poc-operator.css'
import { demoAlternatives, demoDemand, demoDfd, demoEtp, demoItems, demoMatrix, demoMatrixRisks, demoPriceData, demoPriceItems, demoPriceReferences, demoRequirements, demoTr } from './features/procurement/demoProcess'
import type { DemandData, DfdData, InitialRisk, Page, ScopeItem } from './types/process'
import './App.css'

type IconName = 'home'|'process'|'cart'|'document'|'building'|'settings'|'plus'|'menu'|'arrow'|'search'|'more'|'check'

function Icon({name}:{name:IconName}) {
  const paths:Record<IconName,ReactNode>={
    home:<><path d="M3 11 12 3l9 8"/><path d="M5.5 9.5V21h13V9.5M9 21v-7h6v7"/></>, process:<><rect x="4" y="3" width="16" height="18" rx="2"/><path d="M8 8h8M8 12h8M8 16h5"/></>,
    cart:<><path d="M3 4h2l2.3 10a2 2 0 0 0 2 1.6h8a2 2 0 0 0 1.9-1.4L21 8H6"/><circle cx="10" cy="20" r="1"/><circle cx="18" cy="20" r="1"/></>, document:<><path d="M6 2.5h8l4 4V21H6z"/><path d="M14 2.5v4h4M9 11h6M9 15h6"/></>,
    building:<><path d="M4 21V7l8-4 8 4v14M2 21h20M8 10h1M15 10h1M8 14h1M15 14h1M10 21v-4h4v4"/></>, settings:<><circle cx="12" cy="12" r="3"/><path d="M19 15a2 2 0 0 0 .4 2l-2.8 2.8a2 2 0 0 0-2-.4A2 2 0 0 0 13 21H9a2 2 0 0 0-1.2-1.6 2 2 0 0 0-2 .4L3 17a2 2 0 0 0 .4-2A2 2 0 0 0 2 13V9a2 2 0 0 0 1.4-1.2A2 2 0 0 0 3 6l2.8-2.8a2 2 0 0 0 2 .4A2 2 0 0 0 9 2h4a2 2 0 0 0 1.6 1.6 2 2 0 0 0 2-.4L19.4 6a2 2 0 0 0-.4 2A2 2 0 0 0 22 9v4a2 2 0 0 0-3 2Z"/></>,
    plus:<path d="M12 5v14M5 12h14"/>, menu:<path d="M4 7h16M4 12h16M4 17h16"/>, arrow:<path d="m9 18 6-6-6-6"/>, search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>, more:<><circle cx="5" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="19" cy="12" r="1" fill="currentColor"/></>, check:<path d="m5 12 4 4L19 6"/>,
  }
  return <svg className="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>
}

const nav:{label:string;icon:IconName;page?:Page}[]=[
  {label:'POC Deodápolis',icon:'check',page:'poc'},{label:'Modo Demonstração',icon:'arrow',page:'demo'},{label:'Início',icon:'home',page:'home'},{label:'Processos',icon:'process'},{label:'Compras Públicas',icon:'cart',page:'purchases'},{label:'Portal & Diário',icon:'building',page:'portal'},
  {label:'Documentos',icon:'document'},{label:'Departamentos',icon:'building'},{label:'Administração',icon:'settings'},
]
const homeMetrics=[['Processos ativos','12','process','blue'],['Contratações em preparação','5','cart','cyan'],['Documentos','248','document','violet'],['Pendências','7','settings','amber']]
const purchaseMetrics=[['Contratações em planejamento','5','cart','blue'],['DFDs em elaboração','3','document','cyan'],['ETPs em elaboração','2','process','violet'],['Aguardando Termo de Referência','1','document','amber']]
const homeRows=[['001/2026','Aquisição de equipamentos de informática','Administração','DFD','Em elaboração'],['002/2026','Contratação de sistema de gestão','Fazenda','ETP','Em análise'],['003/2026','Serviço de manutenção predial','Infraestrutura','Termo de Referência','Pendente']]
const purchaseRows=[
 ['DEMO','Contratação de plataforma digital de atendimento ao cidadão','Administração','Mariana Costa — DEMO','Aprovação','Demonstração','23/08/2026'],
 ['CP-002/2026','Contratação de sistema integrado de gestão','Fazenda','Paulo Mendes','ETP','Em análise','19/08/2026'],
 ['CP-003/2026','Serviços de manutenção predial','Infraestrutura','Ana Oliveira','Termo de Referência','Pendente','18/08/2026'],
 ['CP-004/2026','Aquisição de materiais escolares','Educação','Roberto Lima','Demanda','Rascunho','17/08/2026'],
]

function Header({eyebrow,title,subtitle,action,onAction}:{eyebrow:string;title:string;subtitle:string;action?:string;onAction?:()=>void}){
 return <header className="topbar"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></div>{action&&<button className="primary" onClick={onAction}><Icon name="plus"/>{action}</button>}</header>
}
function Metrics({items}:{items:string[][]}){return <section className="metrics">{items.map(([label,value,icon,tone])=><article className="metric" key={label}><div><p>{label}</p><strong>{value}</strong></div><span className={`metric-icon ${tone}`}><Icon name={icon as IconName}/></span></article>)}</section>}
function Status({value,index}:{value:string;index:number}){return <span className={`status s${index%4}`}>{value}</span>}

function Home({go}:{go:(p:Page)=>void}){
 return <><Header eyebrow="PAINEL DE GESTÃO" title="Olá, Administrador" subtitle="Visão geral da gestão municipal" action="Novo Processo"/><Metrics items={homeMetrics}/><div className="dashboard">
  <section className="panel processes"><div className="panel-head"><div><h2>Processos recentes</h2><p>Acompanhe os últimos processos cadastrados</p></div><button onClick={()=>go('purchases')}>Ver todos <Icon name="arrow"/></button></div><div className="table-wrap"><table><thead><tr>{['Número','Objeto','Secretaria','Etapa','Status'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{homeRows.map((row,i)=><tr key={row[0]}>{row.map((cell,j)=><td className={j===0?'number':''} key={cell}>{j===4?<Status value={cell} index={i}/>:cell}</td>)}</tr>)}</tbody></table></div></section>
  <section className="panel activity-panel"><div className="panel-head"><div><h2>Atividade recente</h2><p>Últimas movimentações</p></div></div><div className="activity-list">{[['Processo 001/2026 criado','Secretaria de Administração','process'],['DFD 003/2026 atualizado','Secretaria de Educação','document'],['Documento encaminhado para análise','Secretaria de Fazenda','arrow']].map(([title,sub,icon],i)=><div className="activity" key={title}><span className="activity-icon"><Icon name={icon as IconName}/></span><div><strong>{title}</strong><p>{sub}</p><time>{i?'Há 1 hora':'Há 20 minutos'}</time></div></div>)}</div></section>
 </div></>
}

function Purchases({go}:{go:(p:Page)=>void}){
 const [query,setQuery]=useState('')
 const visible=purchaseRows.filter(r=>r.join(' ').toLowerCase().includes(query.toLowerCase()))
 return <><Header eyebrow="COMPRAS PÚBLICAS" title="Compras Públicas" subtitle="Planejamento e acompanhamento das contratações públicas" action="Nova Contratação" onAction={()=>go('new-purchase')}/><Metrics items={purchaseMetrics}/>
  <section className="panel contracts"><div className="panel-head"><div><h2>Contratações</h2><p>Gerencie o ciclo das contratações públicas</p></div></div><div className="filters"><label className="search"><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por número, objeto ou responsável"/></label>{['Secretaria','Etapa','Status'].map(x=><select key={x} aria-label={x}><option>{x}: Todas</option><option>Administração</option><option>Em elaboração</option></select>)}</div>
   <div className="table-wrap"><table className="contracts-table"><thead><tr>{['Número','Objeto','Secretaria','Responsável','Etapa atual','Status','Última atualização','Ações'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{visible.map((row,i)=><tr key={row[0]}>{row.map((cell,j)=><td className={j===0?'number':''} key={`${cell}-${j}`}>{j===5?<Status value={cell} index={i}/>:cell}</td>)}<td><button className="icon-button" aria-label={row[0]==='DEMO'?'Abrir visão geral do processo DEMO':`Ações de ${row[0]}`} onClick={()=>row[0]==='DEMO'&&go('overview')}><Icon name={row[0]==='DEMO'?'arrow':'more'}/></button></td></tr>)}</tbody></table></div>
  </section></>
}

const steps=['Demanda','DFD','ETP','Riscos','Pesquisa de Preços','Termo de Referência','Aprovação']
function Stepper({active}:{active:number}){return <div className="stepper" aria-label="Etapas da contratação">{steps.map((step,i)=><div className={`step ${i===active?'active':''} ${i<active?'done':''}`} key={step}><span>{i<active?<Icon name="check"/>:i+1}</span><small>{step}</small></div>)}</div>}
function Field({label,children,wide=false}:{label:string;children:ReactNode;wide?:boolean}){return <label className={`field ${wide?'wide':''}`}><span>{label}</span>{children}</label>}

const today=new Date().toISOString().slice(0,10)

function NewPurchase({go,data,setData}:{go:(p:Page)=>void;data:DemandData;setData:(d:DemandData)=>void}){
 const [saved,setSaved]=useState(false); const change=(key:keyof DemandData,value:string|boolean)=>setData({...data,[key]:value})
 const submit=(e:FormEvent)=>{e.preventDefault();go('dfd')}
 return <><Header eyebrow="ETAPA 1 DE 7 · COMPRAS PÚBLICAS" title="Nova Contratação" subtitle="Registre a demanda para iniciar o planejamento da contratação"/><Stepper active={0}/><div className="stage-guidance"><div><strong>Você está na Demanda</strong><span>Informe a necessidade da área requisitante. Em seguida, você formalizará o DFD.</span></div><small>Você pode salvar e continuar depois.</small></div>
  {saved&&<div className="toast"><Icon name="check"/> Rascunho salvo localmente.</div>}
  <form className="panel form-panel" onSubmit={submit}><div className="form-section"><div className="section-title"><span>01</span><div><h2>Identificação da demanda</h2><p>Informe os dados iniciais da necessidade administrativa.</p></div></div><div className="form-grid">
   <Field label="Título da contratação"><input required value={data.title} onChange={e=>change('title',e.target.value)} placeholder="Ex.: Aquisição de equipamentos"/></Field><Field label="Objeto resumido"><input required value={data.object} onChange={e=>change('object',e.target.value)} placeholder="Descreva o objeto em uma frase"/></Field>
   <Field label="Secretaria solicitante"><select required value={data.secretariat} onChange={e=>change('secretariat',e.target.value)}><option value="" disabled>Selecione a secretaria</option><option>Administração</option><option>Educação</option><option>Fazenda</option><option>Infraestrutura</option></select></Field><Field label="Setor requisitante"><input value={data.sector} onChange={e=>change('sector',e.target.value)} placeholder="Setor responsável pela solicitação"/></Field>
   <Field label="Responsável pela demanda"><input required value={data.owner} onChange={e=>change('owner',e.target.value)} placeholder="Nome completo"/></Field><Field label="E-mail"><input type="email" value={data.email} onChange={e=>change('email',e.target.value)} placeholder="nome@municipio.gov.br"/></Field><Field label="Telefone/Ramal"><input value={data.phone} onChange={e=>change('phone',e.target.value)} placeholder="(00) 0000-0000 / Ramal"/></Field>
   <Field label="Tipo de contratação"><select value={data.type} onChange={e=>change('type',e.target.value)}><option value="" disabled>Selecione o tipo</option><option>Aquisição de bens</option><option>Contratação de serviços</option><option>Obras e serviços de engenharia</option></select></Field><Field label="Prioridade"><select value={data.priority} onChange={e=>change('priority',e.target.value)}><option>Normal</option><option>Alta</option><option>Urgente</option></select></Field>
   <Field label="Data desejada para contratação"><input type="date" value={data.desiredDate} onChange={e=>change('desiredDate',e.target.value)}/></Field><Field label="Valor estimado preliminar"><input value={data.estimatedValue} onChange={e=>change('estimatedValue',e.target.value)} placeholder="R$ 0,00" inputMode="decimal"/></Field>
  </div></div><div className="form-section"><div className="section-title"><span>02</span><div><h2>Justificativa e resultados</h2><p>Contextualize a necessidade que será atendida.</p></div></div><div className="form-grid">
   <Field wide label="Descrição da necessidade"><textarea rows={4} value={data.need} onChange={e=>change('need',e.target.value)} placeholder="Descreva detalhadamente a necessidade da contratação..."/></Field><Field wide label="Problema que precisa ser resolvido"><textarea rows={4} value={data.problem} onChange={e=>change('problem',e.target.value)} placeholder="Qual problema público ou administrativo será resolvido?"/></Field><Field wide label="Resultado esperado"><textarea rows={4} value={data.result} onChange={e=>change('result',e.target.value)} placeholder="Quais resultados e benefícios são esperados?"/></Field>
  </div></div><div className="form-section pca-section"><label className="checkbox"><input type="checkbox" checked={data.pca} onChange={e=>change('pca',e.target.checked)}/><span><b>Contratação prevista no PCA</b><small>Plano de Contratações Anual</small></span></label>{data.pca&&<Field label="Número/identificação do item no PCA"><input value={data.pcaItem} onChange={e=>change('pcaItem',e.target.value)} placeholder="Ex.: PCA-2026 / Item 042"/></Field>}</div>
  <div className="form-actions"><button type="button" className="secondary" onClick={()=>setSaved(true)}>Salvar rascunho</button><button className="primary" type="submit">Continuar para DFD <Icon name="arrow"/></button></div></form></>
}

function Dfd({go,demand,setDemand,dfd,setDfd,items,setItems,risks,setRisks}:{go:(p:Page)=>void;demand:DemandData;setDemand:(d:DemandData)=>void;dfd:DfdData;setDfd:(d:DfdData)=>void;items:ScopeItem[];setItems:(i:ScopeItem[])=>void;risks:InitialRisk[];setRisks:(r:InitialRisk[])=>void}){
 const [saved,setSaved]=useState(false); const change=(key:keyof DfdData,value:string)=>setDfd({...dfd,[key]:value}); const inherited=(key:keyof DemandData,value:string)=>setDemand({...demand,[key]:value})
 const updateItem=(id:number,key:keyof ScopeItem,value:string)=>setItems(items.map(x=>x.id===id?{...x,[key]:value}:x)); const updateRisk=(id:number,key:keyof InitialRisk,value:string)=>setRisks(risks.map(x=>x.id===id?{...x,[key]:value}:x))
 return <><Header eyebrow="ETAPA 2 DE 7 · COMPRAS PÚBLICAS" title="DFD — Documento de Formalização da Demanda" subtitle="Registra oficialmente a necessidade de contratação apresentada pela área requisitante."/><Stepper active={1}/><div className="stage-guidance"><div><strong>Você está no DFD</strong><span>Formalize a necessidade e o escopo inicial. A próxima etapa será o Estudo Técnico Preliminar.</span></div><small>Você pode salvar e continuar depois.</small></div>
  <div className="process-strip"><div><small>Processo</small><strong>Rascunho</strong></div><div><small>Secretaria</small><strong>{demand.secretariat||'Não informada'}</strong></div><div><small>Responsável</small><strong>{demand.owner||'Não informado'}</strong></div><div><small>Status</small><Status value={dfd.status} index={0}/></div></div>{saved&&<div className="toast"><Icon name="check"/> DFD salvo localmente.</div>}
  <form className="panel form-panel" onSubmit={e=>e.preventDefault()}>
   <DfdSection number="01" title="Identificação" text="Dados aproveitados automaticamente da etapa Demanda."><div className="inherit-note"><Icon name="check"/> Campos com fundo azul foram herdados da Demanda e permanecem sincronizados.</div><div className="form-grid inherited-grid">
    <Field label="Título da contratação"><input value={demand.title} onChange={e=>inherited('title',e.target.value)}/></Field><Field label="Objeto resumido"><input value={demand.object} onChange={e=>inherited('object',e.target.value)}/></Field><Field label="Secretaria solicitante"><input value={demand.secretariat} readOnly/></Field><Field label="Setor requisitante"><input value={demand.sector} readOnly/></Field><Field label="Responsável pela demanda"><input value={demand.owner} readOnly/></Field><Field label="Data da demanda"><input type="date" value={today} readOnly/></Field><Field label="Prioridade"><input value={demand.priority} readOnly/></Field>
   </div></DfdSection>
   <DfdSection number="02" title="Necessidade da contratação" text="Aprofunde a justificativa construída na Demanda."><div className="form-grid"><Field wide label="Descrição detalhada da necessidade"><textarea className="inherited" value={demand.need} readOnly rows={4}/><GovCopilot action="Me ajude a escrever" context={[demand.object,demand.secretariat,'Descrição da Demanda']} value={demand.need} onChange={value=>inherited('need',value)} suggestions={['DEMO — A Administração necessita centralizar os canais de atendimento ao cidadão em uma plataforma acessível, rastreável e capaz de fornecer informações claras sobre cada solicitação.']}/></Field><Field wide label="Problema administrativo ou público a ser resolvido"><textarea className="inherited" value={demand.problem} readOnly rows={4}/><GovCopilot action="Me ajude a escrever" context={[demand.need,'Problema registrado na Demanda']} value={demand.problem} onChange={value=>inherited('problem',value)} suggestions={['DEMO — A dispersão dos atendimentos entre balcão, telefone e mensagens impede o acompanhamento uniforme, aumenta o retrabalho e reduz a transparência para o cidadão.']}/></Field><Field wide label="Justificativa da contratação"><textarea value={dfd.justification} onChange={e=>change('justification',e.target.value)} rows={4} placeholder="Fundamente por que a contratação é necessária..."/><GovCopilot action="Me ajude a escrever" context={[demand.need,demand.problem,demand.result]} value={dfd.justification} onChange={value=>change('justification',value)} suggestions={['DEMO — A contratação se justifica pela necessidade de padronizar o atendimento, garantir rastreabilidade das solicitações e produzir indicadores que apoiem a melhoria contínua dos serviços públicos.']}/></Field><Field wide label="Resultado esperado"><textarea className="inherited" value={demand.result} readOnly rows={3}/><GovCopilot action="Me ajude a escrever" context={[demand.need,demand.problem]} value={demand.result} onChange={value=>inherited('result',value)} suggestions={['DEMO — Espera-se reduzir o tempo médio de resposta, permitir acompanhamento pelo cidadão e disponibilizar indicadores confiáveis para a gestão municipal.']}/></Field><Field wide label="Benefícios esperados"><textarea value={dfd.benefits} onChange={e=>change('benefits',e.target.value)} rows={3} placeholder="Liste os benefícios para a administração e para a população..."/></Field></div></DfdSection>
   <DfdSection number="03" title="Quantidade e escopo preliminar" text="Detalhe os itens previstos sem fechar a solução técnica."><div className="editable-table"><div className="edit-row edit-head"><span>Item</span><span>Descrição</span><span>Quantidade</span><span>Unidade</span><span>Observação</span><span/></div>{items.map((item,i)=><div className="edit-row" key={item.id}><b>{i+1}</b><input value={item.description} onChange={e=>updateItem(item.id,'description',e.target.value)} placeholder="Descrição do item"/><input value={item.quantity} onChange={e=>updateItem(item.id,'quantity',e.target.value)} inputMode="numeric"/><input value={item.unit} onChange={e=>updateItem(item.id,'unit',e.target.value)} placeholder="Unidade"/><input value={item.note} onChange={e=>updateItem(item.id,'note',e.target.value)} placeholder="Opcional"/><button type="button" onClick={()=>setItems(items.filter(x=>x.id!==item.id))}>×</button></div>)}</div><button type="button" className="add-button" onClick={()=>setItems([...items,{id:Date.now(),description:'',quantity:'1',unit:'unidade',note:''}])}><Icon name="plus"/>Adicionar item</button></DfdSection>
   <DfdSection number="04" title="Alinhamento com o planejamento" text="Relacione a demanda aos instrumentos de planejamento municipal."><label className="checkbox inline-check"><input type="checkbox" checked={demand.pca} readOnly/><span><b>Previsto no PCA</b><small>Informação herdada da Demanda</small></span></label>{demand.pca&&<div className="form-grid"><Field label="Ano do PCA"><input value={dfd.pcaYear} onChange={e=>change('pcaYear',e.target.value)}/></Field><Field label="Código/Item do PCA"><input value={demand.pcaItem} readOnly/></Field></div>}<div className="form-grid section-gap"><Field wide label="Alinhamento com planejamento estratégico"><textarea value={dfd.strategicAlignment} onChange={e=>change('strategicAlignment',e.target.value)} rows={3}/></Field><Field wide label="Programa/Ação orçamentária, quando conhecida"><input value={dfd.budgetAction} onChange={e=>change('budgetAction',e.target.value)} placeholder="Opcional nesta etapa"/></Field></div></DfdSection>
   <DfdSection number="05" title="Previsão da contratação" text="Consolide as estimativas iniciais informadas pela área demandante."><div className="form-grid"><Field label="Data desejada"><input className="inherited" type="date" value={demand.desiredDate} readOnly/></Field><Field label="Valor preliminar estimado"><input className="inherited" value={demand.estimatedValue} readOnly/></Field><Field label="Fonte do valor preliminar"><input value={dfd.valueSource} onChange={e=>change('valueSource',e.target.value)} placeholder="Ex.: contratação anterior"/></Field><Field label="Grau de prioridade"><input className="inherited" value={demand.priority} readOnly/></Field><Field label="Contratação continuada?"><select value={dfd.continued} onChange={e=>change('continued',e.target.value)}><option>Não</option><option>Sim</option></select></Field><Field label="Prazo inicial estimado do contrato"><input value={dfd.contractTerm} onChange={e=>change('contractTerm',e.target.value)} placeholder="Ex.: 12 meses"/></Field></div></DfdSection>
   <DfdSection number="06" title="Riscos iniciais da não contratação" text="Registre consequências preliminares, sem formar ainda a Matriz de Riscos."><div className="form-grid"><Field wide label="O que pode acontecer se esta contratação não for realizada?"><textarea value={dfd.nonContracting} onChange={e=>change('nonContracting',e.target.value)} rows={4}/></Field></div><div className="risk-list">{risks.map(r=><div className="risk-row" key={r.id}><input value={r.risk} onChange={e=>updateRisk(r.id,'risk',e.target.value)} placeholder="Risco"/><select value={r.impact} onChange={e=>updateRisk(r.id,'impact',e.target.value)}><option>Baixo</option><option>Médio</option><option>Alto</option></select><input value={r.note} onChange={e=>updateRisk(r.id,'note',e.target.value)} placeholder="Observação"/><button type="button" onClick={()=>setRisks(risks.filter(x=>x.id!==r.id))}>×</button></div>)}</div><button type="button" className="add-button" onClick={()=>setRisks([...risks,{id:Date.now(),risk:'',impact:'Médio',note:''}])}><Icon name="plus"/>Adicionar risco preliminar</button></DfdSection>
   <DfdSection number="07" title="Responsáveis" text="Identifique os agentes do fluxo; assinaturas serão tratadas posteriormente."><div className="form-grid"><Field label="Demandante"><input className="inherited" value={demand.owner} readOnly/></Field><Field label="Responsável pela elaboração do DFD"><input value={dfd.drafter} onChange={e=>change('drafter',e.target.value)} placeholder="Nome do responsável"/></Field><Field label="Autoridade/setor para encaminhamento"><input value={dfd.authority} onChange={e=>change('authority',e.target.value)} placeholder="Autoridade ou setor"/></Field><Field label="Status visual"><select value={dfd.status} onChange={e=>change('status',e.target.value)}><option>Não encaminhado</option><option>Em elaboração</option><option>Pronto para encaminhar</option></select></Field></div></DfdSection>
   <div className="form-actions dfd-actions"><button type="button" className="secondary" onClick={()=>go('new-purchase')}>Voltar para Demanda</button><span/><button type="button" className="secondary" onClick={()=>setSaved(true)}>Salvar rascunho</button><button type="button" className="outline-primary" onClick={()=>change('status','Pronto para encaminhar')}><Icon name="check"/>Marcar DFD como concluído</button><button type="button" className="primary" onClick={()=>go('etp')}>Continuar para ETP <Icon name="arrow"/></button></div>
  </form></>
}
function DfdSection({number,title,text,children}:{number:string;title:string;text:string;children:ReactNode}){return <section className="form-section"><div className="section-title"><span>{number}</span><div><h2>{title}</h2><p>{text}</p></div></div>{children}</section>}
export default function App(){
 const [page,setPage]=useState<Page>(()=>/^\/(noticias|paginas|documentos|diario)\//.test(location.pathname)?'portal':'home'); const [open,setOpen]=useState(false)
 const [demand,setDemand]=useState<DemandData>({...demoDemand})
 const [dfd,setDfd]=useState<DfdData>({...demoDfd})
 const [items,setItems]=useState<ScopeItem[]>(demoItems.map(x=>({...x}))); const [risks,setRisks]=useState<InitialRisk[]>([])
 const [etp,setEtp]=useState<EtpData>({...demoEtp})
 const [requirements,setRequirements]=useState<Requirement[]>(demoRequirements.map(x=>({...x})))
 const [alternatives,setAlternatives]=useState<Alternative[]>(demoAlternatives.map(x=>({...x})))
 const [related,setRelated]=useState<Related[]>([]); const [indicators,setIndicators]=useState<Indicator[]>([])
 const [preparations,setPreparations]=useState<Preparation[]>(['Adequação de infraestrutura','Capacitação de servidores','Migração de dados','Integrações','Criação de usuários/perfis','Ajustes normativos','Outra providência'].map((kind,i)=>({id:i+1,kind,responsible:'',deadline:'',note:'',done:false})))
 const [matrix,setMatrix]=useState<RiskMatrixData>({...demoMatrix}); const [matrixRisks,setMatrixRisks]=useState<RiskItem[]>(demoMatrixRisks.map(x=>({...x})))
 const [priceData,setPriceData]=useState<PriceData>({...demoPriceData}); const [priceItems,setPriceItems]=useState<PriceItem[]>(demoPriceItems.map(x=>({...x}))); const [priceReferences,setPriceReferences]=useState<PriceReference[]>(demoPriceReferences.map(x=>({...x})))
 const [tr,setTr]=useState<TrData>({...demoTr}); const [milestones,setMilestones]=useState<Milestone[]>([]); const [slas,setSlas]=useState<Sla[]>([{id:1,indicator:'Disponibilidade mensal — DEMO',target:'99,5%',measurement:'Relatório da plataforma',frequency:'Mensal',consequence:'Plano de correção'}])
 const [reviewed,setReviewed]=useState<string[]>([]); const [reviewReturn,setReviewReturn]=useState<Page>('tr'); const [trFocus,setTrFocus]=useState<number|undefined>()
 const go=(next:Page)=>{setPage(next);setOpen(false);window.scrollTo({top:0,behavior:'smooth'})}
 const openPrices=()=>{if(priceItems.length===0)setPriceItems(items.map(x=>({id:x.id,description:x.description,quantity:x.quantity,unit:x.unit,currentEstimate:'',method:'Mediana',customValue:''})));go('prices')}
 const openReview=()=>{setReviewReturn(page);go('review')}; const correctIssue=(target:ReviewStage,section?:number)=>{if(target==='tr')setTrFocus(section);go(target)}
 const reviewContext:ReviewContext={object:demand.object,need:demand.need,dfdNeed:demand.need,solution:etp.recommended,nature:etp.nature,etp,requirements,risks:matrixRisks,priceItems,references:priceReferences,dfdItems:items,preliminaryValue:demand.estimatedValue,tr,continued:dfd.continued,contractTerm:dfd.contractTerm,pca:demand.pca,pcaItem:demand.pcaItem}
 const reviewIssues=runReview(reviewContext)
 const alertsFor=(stage:string)=>reviewIssues.filter(issue=>issue.stage===stage).length
 const approvalStages=[
  {label:'Demanda',status:'Concluída',responsible:demand.owner,updated:'23/08/2026 · DEMO',alerts:alertsFor('Demanda'),page:'new-purchase' as Page},
  {label:'DFD',status:dfd.status,responsible:dfd.drafter,updated:'23/08/2026 · DEMO',alerts:alertsFor('DFD'),page:'dfd' as Page},
  {label:'ETP',status:etp.status,responsible:etp.drafter,updated:'23/08/2026 · DEMO',alerts:alertsFor('ETP'),page:'etp' as Page},
  {label:'Matriz de Riscos',status:matrix.status,responsible:'Equipe de planejamento — DEMO',updated:'23/08/2026 · DEMO',alerts:alertsFor('Matriz de Riscos'),page:'risks' as Page},
  {label:'Pesquisa de Preços',status:priceData.status,responsible:priceData.responsible,updated:'23/08/2026 · DEMO',alerts:alertsFor('Pesquisa de Preços'),page:'prices' as Page},
  {label:'Termo de Referência',status:tr.status,responsible:tr.drafter,updated:'23/08/2026 · DEMO',alerts:alertsFor('Termo de Referência'),page:'tr' as Page},
  {label:'Revisão Inteligente',status:'Executada',responsible:'GOV TOTAL · regras locais',updated:'23/08/2026 · DEMO',alerts:reviewIssues.length,page:'review' as Page},
 ]
 const overviewStages:OverviewStage[]=[
  {label:'Demanda',summary:'Necessidade de atendimento digital registrada.',status:'Concluída',page:'new-purchase'},
  {label:'DFD',summary:'Necessidade, escopo e planejamento formalizados.',status:dfd.status,page:'dfd'},
  {label:'ETP',summary:'Solução SaaS avaliada como viável.',status:etp.status,page:'etp'},
  {label:'Riscos',summary:'Riscos e tratamentos iniciais definidos.',status:matrix.status,page:'risks'},
  {label:'Pesquisa',summary:'Referências DEMO comparadas pela mediana.',status:priceData.status,page:'prices'},
  {label:'TR',summary:'Requisitos, execução e fiscalização consolidados.',status:tr.status,page:'tr'},
  {label:'Aprovação',summary:'Planejamento pronto para parecer demonstrativo.',status:'Em análise',page:'approval'},
 ]
 return <div className="app-shell">
  <button className="mobile-menu" onClick={()=>setOpen(true)} aria-label="Abrir menu"><Icon name="menu"/></button>{open&&<button className="overlay" onClick={()=>setOpen(false)} aria-label="Fechar menu"/>}
  <aside className={`sidebar ${open?'open':''}`}><div className="brand"><div className="brand-mark">GT</div><div><strong>GOV TOTAL</strong><span>Gestão Pública Inteligente</span></div></div><nav><small>MENU PRINCIPAL</small>{nav.map(item=><button title={item.label} className={`nav-item ${(item.page===page||(item.page==='purchases'&&['overview','new-purchase','dfd','etp','risks','prices','tr','review','approval'].includes(page)))?'active':''}`} key={item.label} onClick={()=>item.page&&go(item.page)}><Icon name={item.icon}/>{item.label}</button>)}</nav><div className="sidebar-footer"><span className="city-icon"><Icon name="building"/></span><div><strong>Prefeitura Municipal</strong><span><i/> Ambiente DEMO</span></div></div></aside>
  <main>
   {page==='portal'&&<PortalModule/>} {page==='poc'&&<><PocDashboard/><PocOperatorGuide onNavigate={go}/><EmailProviderComparator/></>}
   {page==='demo'&&<DemoMode onExit={()=>go('home')}/>} 
   {!['portal','poc','demo','home','purchases','overview','review','approval'].includes(page)&&<button className="global-review-button" onClick={openReview}><Icon name="check"/> Revisar processo</button>}
   {page==='home'&&<Home go={go}/>} {page==='purchases'&&<Purchases go={go}/>} {page==='overview'&&<ProcessOverview data={{object:demand.object,secretariat:demand.secretariat,owner:demand.owner,status:'Em análise · DEMO',value:demand.estimatedValue,desiredDate:'30/11/2026'}} stages={overviewStages} currentPage="approval" onNavigate={go}/>} {page==='new-purchase'&&<NewPurchase go={go} data={demand} setData={setDemand}/>} {page==='dfd'&&<Dfd go={go} demand={demand} setDemand={setDemand} dfd={dfd} setDfd={setDfd} items={items} setItems={setItems} risks={risks} setRisks={setRisks}/>} {page==='etp'&&<Etp context={{object:demand.object,need:demand.need,problem:demand.problem,result:demand.result,estimatedValue:demand.estimatedValue,secretariat:demand.secretariat,owner:demand.owner,items}} data={etp} setData={setEtp} requirements={requirements} setRequirements={setRequirements} alternatives={alternatives} setAlternatives={setAlternatives} related={related} setRelated={setRelated} indicators={indicators} setIndicators={setIndicators} preparations={preparations} setPreparations={setPreparations} onBack={()=>go('dfd')} onContinue={()=>go('risks')}/>} {page==='risks'&&<RiskMatrix context={{object:demand.object,secretariat:demand.secretariat,owner:demand.owner,estimatedValue:demand.estimatedValue,solution:etp.recommended}} data={matrix} setData={setMatrix} risks={matrixRisks} setRisks={setMatrixRisks} onBack={()=>go('etp')} onContinue={openPrices}/>} {page==='prices'&&<PriceResearch context={{object:demand.object,secretariat:demand.secretariat,solution:etp.recommended,preliminaryValue:demand.estimatedValue}} items={priceItems} setItems={setPriceItems} references={priceReferences} setReferences={setPriceReferences} data={priceData} setData={setPriceData} onBack={()=>go('risks')} onContinue={()=>go('tr')}/>} {page==='tr'&&<TermReference focusSection={trFocus} context={{secretariat:demand.secretariat,owner:demand.owner,object:demand.object,solution:etp.recommended,solutionDescription:etp.solutionDescription,nature:etp.nature,need:demand.need,problem:demand.problem,justification:dfd.justification,results:etp.results,viabilityConclusion:etp.conclusion,sustainability:etp.sustainability,items,requirements,risks:matrixRisks,priceItems,references:priceReferences,methodologyReason:priceData.methodologyReason}} data={tr} setData={setTr} milestones={milestones} setMilestones={setMilestones} slas={slas} setSlas={setSlas} requirements={requirements} setRequirements={setRequirements} onBack={()=>go('prices')} onRisks={()=>go('risks')} onContinue={()=>{setReviewReturn('tr');go('review')}}/>} {page==='review'&&<SmartReview context={reviewContext} reviewed={reviewed} setReviewed={setReviewed} onBack={()=>reviewReturn==='tr'?go('approval'):go(reviewReturn)} onCorrect={correctIssue}/>} {page==='approval'&&<Approval stages={approvalStages} issues={reviewIssues} onNavigate={go}/>} 
   {page==='approval'&&<div className="overview-shortcut"><button className="primary" onClick={()=>go('overview')}>Abrir Visão Geral do Processo <Icon name="arrow"/></button></div>}
   <footer>Dados demonstrativos para validação visual do GOV TOTAL.</footer>
  </main>
 </div>
}
