import { useState, type ReactNode } from 'react'
import GovCopilot from './components/GovCopilot'

export type Requirement={id:number;title:string;description:string;type:string}
export type Alternative={id:number;name:string;description:string;advantages:string;disadvantages:string;cost:string;viability:string}
export type Related={id:number;object:string;process:string;department:string;relation:string}
export type Indicator={id:number;name:string;target:string;measurement:string}
export type Preparation={id:number;kind:string;responsible:string;deadline:string;note:string;done:boolean}
export type EtpData={recommended:string;solutionDescription:string;choiceReason:string;rejectionReason:string;nature:string;methodology:string;sources:string;baseDate:string;parceling:string;parcelingReason:string;hasRelated:boolean;results:string;adminBenefits:string;citizenBenefits:string;environmentalImpact:string;mitigation:string;sustainability:string;sustainabilityNA:boolean;viable:string;conclusion:string;drafter:string;status:string}
export type ProcessContext={object:string;need:string;problem:string;result:string;estimatedValue:string;secretariat:string;owner:string;items:{id:number;description:string;quantity:string;unit:string;note:string}[]}

const steps=['Demanda','DFD','ETP','Riscos','Pesquisa de Preços','Termo de Referência','Aprovação']
function Stepper(){return <div className="stepper">{steps.map((s,i)=><div className={`step ${i===2?'active':''} ${i<2?'done':''}`} key={s}><span>{i<2?'✓':i+1}</span><small>{s}</small></div>)}</div>}
function Section({number,title,text,children}:{number:string;title:string;text:string;children:ReactNode}){return <section className="form-section"><div className="section-title"><span>{number}</span><div><h2>{title}</h2><p>{text}</p></div></div>{children}</section>}
function Field({label,children,wide=false}:{label:string;children:ReactNode;wide?:boolean}){return <label className={`field ${wide?'wide':''}`}><span>{label}</span>{children}</label>}
const requirementTypes=['Funcional','Técnico','Segurança','Desempenho','Implantação','Suporte','Integração','Legal/regulatório','Acessibilidade','Sustentabilidade','Outro']

export default function Etp({context,data,setData,requirements,setRequirements,alternatives,setAlternatives,related,setRelated,indicators,setIndicators,preparations,setPreparations,onBack,onContinue}:{context:ProcessContext;data:EtpData;setData:(v:EtpData)=>void;requirements:Requirement[];setRequirements:(v:Requirement[])=>void;alternatives:Alternative[];setAlternatives:(v:Alternative[])=>void;related:Related[];setRelated:(v:Related[])=>void;indicators:Indicator[];setIndicators:(v:Indicator[])=>void;preparations:Preparation[];setPreparations:(v:Preparation[])=>void;onBack:()=>void;onContinue:()=>void}){
 const [saved,setSaved]=useState(false); const change=(key:keyof EtpData,value:string|boolean)=>setData({...data,[key]:value})
 const update=<T extends {id:number}>(list:T[],setList:(v:T[])=>void,id:number,key:keyof T,value:string|boolean)=>setList(list.map(x=>x.id===id?{...x,[key]:value}:x))
 return <><header className="topbar"><div><span className="eyebrow">ETAPA 3 DE 7 · COMPRAS PÚBLICAS</span><h1>ETP — Estudo Técnico Preliminar</h1><p>Documento utilizado para analisar o problema, as alternativas disponíveis e justificar a solução escolhida.</p></div></header><Stepper/><div className="stage-guidance"><div><strong>Você está no Estudo Técnico Preliminar</strong><span>Compare alternativas e justifique a solução mais adequada. Depois, você avaliará os riscos.</span></div><small>Você pode salvar e continuar depois.</small></div>
  <div className="process-strip"><div><small>Processo</small><strong>Rascunho</strong></div><div><small>Secretaria</small><strong>{context.secretariat||'Não informada'}</strong></div><div><small>Responsável</small><strong>{context.owner||'Não informado'}</strong></div><div><small>Status</small><span className="status s0">{data.status}</span></div></div>{saved&&<div className="toast">✓ ETP salvo localmente.</div>}
  <form className="panel form-panel" onSubmit={e=>e.preventDefault()}>
   <div className="copilot-toolbar"><strong>✨ Assistência disponível nesta etapa</strong><div><GovCopilot action="Sugerir alternativas para analisar" context={[context.object,context.need,'Requisitos cadastrados']} value="" onChange={()=>setAlternatives([{id:Date.now(),name:'DEMO — Desenvolvimento próprio',description:'Avaliar capacidade interna e prazo.',advantages:'Maior controle.',disadvantages:'Exige equipe especializada.',cost:'A estimar',viability:'Parcialmente viável'},{id:Date.now()+1,name:'DEMO — Contratação SaaS',description:'Plataforma em nuvem oferecida como serviço.',advantages:'Implantação mais rápida.',disadvantages:'Dependência do fornecedor.',cost:context.estimatedValue,viability:'Viável'},{id:Date.now()+2,name:'DEMO — Solução compartilhada',description:'Uso de solução adotada por outro órgão.',advantages:'Possível economia.',disadvantages:'Adequação limitada.',cost:'A estimar',viability:'Em análise'}])} suggestions={['DEMO — Compare desenvolvimento próprio, contratação SaaS e solução compartilhada com outro órgão.']}/><GovCopilot action="Ajudar a justificar a escolha" context={[context.need,data.recommended,`${alternatives.length} alternativas analisadas`]} value={data.choiceReason} onChange={value=>change('choiceReason',value)} suggestions={['DEMO — A solução SaaS apresenta melhor equilíbrio entre prazo de implantação, atualização contínua, suporte especializado e custo previsível, sem exigir estrutura própria de desenvolvimento.']}/><GovCopilot action="Revisar conclusão" context={[data.recommended,data.choiceReason,context.estimatedValue]} value={data.conclusion} onChange={value=>change('conclusion',value)} suggestions={['DEMO — Considerando a necessidade, os requisitos, as alternativas e a estimativa preliminar, a contratação é viável, condicionada à validação da pesquisa de preços e dos níveis mínimos de serviço.']}/></div></div>
   <Section number="01" title="Contexto da necessidade" text="Informações consolidadas nas etapas Demanda e DFD."><div className="inherit-note">✓ Os campos em azul foram herdados e evitam redigitação.</div><div className="form-grid inherited-grid"><Field label="Objeto"><input value={context.object} readOnly/></Field><Field label="Resultado esperado"><input value={context.result} readOnly/></Field><Field wide label="Necessidade"><textarea value={context.need} readOnly rows={3}/></Field><Field wide label="Problema a resolver"><textarea value={context.problem} readOnly rows={3}/></Field></div><div className="inherited-scope"><strong>Itens / escopo preliminar</strong>{context.items.map((x,i)=><div key={x.id}><span>{i+1}</span><p>{x.description||'Item sem descrição'}</p><b>{x.quantity} {x.unit}</b></div>)}</div></Section>
   <Section number="02" title="Requisitos da contratação" text="Defina somente os requisitos necessários para avaliar a solução."><EditableList items={requirements} onRemove={id=>setRequirements(requirements.filter(x=>x.id!==id))} onAdd={()=>setRequirements([...requirements,{id:Date.now(),title:'',description:'',type:'Funcional'}])} addLabel="Adicionar requisito">{r=><><input value={r.title} onChange={e=>update(requirements,setRequirements,r.id,'title',e.target.value)} placeholder="Título do requisito"/><textarea value={r.description} onChange={e=>update(requirements,setRequirements,r.id,'description',e.target.value)} placeholder="Descrição"/><select value={r.type} onChange={e=>update(requirements,setRequirements,r.id,'type',e.target.value)}>{requirementTypes.map(t=><option key={t}>{t}</option>)}</select></>}</EditableList></Section>
   <Section number="03" title="Levantamento de alternativas" text="Compare possibilidades sem gerar conteúdo automaticamente."><div className="alternative-list">{alternatives.map((a,i)=><article className="alternative-card" key={a.id}><div className="alternative-title"><span>Alternativa {i+1}</span><button type="button" onClick={()=>setAlternatives(alternatives.filter(x=>x.id!==a.id))}>Remover</button></div><div className="form-grid"><Field label="Nome da alternativa"><input value={a.name} onChange={e=>update(alternatives,setAlternatives,a.id,'name',e.target.value)} placeholder="Ex.: Contratação SaaS"/></Field><Field label="Viabilidade"><select value={a.viability} onChange={e=>update(alternatives,setAlternatives,a.id,'viability',e.target.value)}><option>Em análise</option><option>Viável</option><option>Parcialmente viável</option><option>Inviável</option></select></Field><Field wide label="Descrição"><textarea rows={2} value={a.description} onChange={e=>update(alternatives,setAlternatives,a.id,'description',e.target.value)}/></Field><Field label="Vantagens"><textarea rows={3} value={a.advantages} onChange={e=>update(alternatives,setAlternatives,a.id,'advantages',e.target.value)}/></Field><Field label="Desvantagens"><textarea rows={3} value={a.disadvantages} onChange={e=>update(alternatives,setAlternatives,a.id,'disadvantages',e.target.value)}/></Field><Field label="Custo preliminar"><input value={a.cost} onChange={e=>update(alternatives,setAlternatives,a.id,'cost',e.target.value)} placeholder="R$ 0,00"/></Field></div></article>)}</div><button type="button" className="add-button" onClick={()=>setAlternatives([...alternatives,{id:Date.now(),name:'',description:'',advantages:'',disadvantages:'',cost:'',viability:'Em análise'}])}>＋ Adicionar alternativa</button></Section>
   <Section number="04" title="Solução escolhida" text="Registre a decisão após comparar as alternativas."><div className="form-grid"><Field label="Solução recomendada"><input value={data.recommended} onChange={e=>change('recommended',e.target.value)}/></Field><Field label="Natureza da solução"><select value={data.nature} onChange={e=>change('nature',e.target.value)}><option>Serviço</option><option>Software/SaaS</option><option>Aquisição</option><option>Serviço continuado</option><option>Solução integrada</option><option>Outro</option></select></Field><Field wide label="Descrição da solução"><textarea rows={4} value={data.solutionDescription} onChange={e=>change('solutionDescription',e.target.value)}/></Field><Field wide label="Justificativa da escolha"><textarea rows={4} value={data.choiceReason} onChange={e=>change('choiceReason',e.target.value)}/></Field><Field wide label="Motivo da rejeição das demais alternativas"><textarea rows={3} value={data.rejectionReason} onChange={e=>change('rejectionReason',e.target.value)}/></Field></div></Section>
   <Section number="05" title="Estimativa preliminar" text="Registre a base da estimativa utilizada nesta análise."><div className="form-grid"><Field label="Valor estimado preliminar"><input className="inherited" value={context.estimatedValue} readOnly/></Field><Field label="Metodologia utilizada"><input value={data.methodology} onChange={e=>change('methodology',e.target.value)}/></Field><Field wide label="Fontes consideradas"><textarea rows={3} value={data.sources} onChange={e=>change('sources',e.target.value)}/></Field><Field label="Data-base da estimativa"><input type="date" value={data.baseDate} onChange={e=>change('baseDate',e.target.value)}/></Field></div><div className="info-notice">A estimativa do ETP não substitui a Pesquisa de Preços formal.</div></Section>
   <Section number="06" title="Parcelamento" text="Avalie se dividir a solução amplia a competitividade sem prejudicar o resultado."><div className="form-grid"><Field label="A solução pode ser parcelada/dividida?"><select value={data.parceling} onChange={e=>change('parceling',e.target.value)}><option>Em análise</option><option>Sim</option><option>Não</option></select></Field><Field wide label="Justificativa"><textarea rows={3} value={data.parcelingReason} onChange={e=>change('parcelingReason',e.target.value)}/></Field></div></Section>
   <Section number="07" title="Contratações relacionadas" text="Identifique relações que possam afetar o planejamento."><label className="checkbox inline-check"><input type="checkbox" checked={data.hasRelated} onChange={e=>change('hasRelated',e.target.checked)}/><span><b>Existem contratações correlatas ou interdependentes</b></span></label>{data.hasRelated&&<EditableList items={related} onRemove={id=>setRelated(related.filter(x=>x.id!==id))} onAdd={()=>setRelated([...related,{id:Date.now(),object:'',process:'',department:'',relation:''}])} addLabel="Adicionar contratação relacionada">{r=><><input value={r.object} onChange={e=>update(related,setRelated,r.id,'object',e.target.value)} placeholder="Objeto"/><input value={r.process} onChange={e=>update(related,setRelated,r.id,'process',e.target.value)} placeholder="Contrato/processo"/><input value={r.department} onChange={e=>update(related,setRelated,r.id,'department',e.target.value)} placeholder="Órgão/setor"/><textarea value={r.relation} onChange={e=>update(related,setRelated,r.id,'relation',e.target.value)} placeholder="Relação com esta contratação"/></>}</EditableList>}</Section>
   <Section number="08" title="Resultados pretendidos" text="Defina benefícios verificáveis e indicadores preliminares."><div className="form-grid"><Field wide label="Resultados esperados"><textarea rows={3} value={data.results} onChange={e=>change('results',e.target.value)}/></Field><Field label="Benefícios para a Administração"><textarea rows={3} value={data.adminBenefits} onChange={e=>change('adminBenefits',e.target.value)}/></Field><Field label="Benefícios para o cidadão, quando aplicável"><textarea rows={3} value={data.citizenBenefits} onChange={e=>change('citizenBenefits',e.target.value)}/></Field></div><h3 className="subheading">Indicadores preliminares de sucesso</h3><EditableList items={indicators} onRemove={id=>setIndicators(indicators.filter(x=>x.id!==id))} onAdd={()=>setIndicators([...indicators,{id:Date.now(),name:'',target:'',measurement:''}])} addLabel="Adicionar indicador">{r=><><input value={r.name} onChange={e=>update(indicators,setIndicators,r.id,'name',e.target.value)} placeholder="Indicador"/><input value={r.target} onChange={e=>update(indicators,setIndicators,r.id,'target',e.target.value)} placeholder="Meta preliminar"/><input value={r.measurement} onChange={e=>update(indicators,setIndicators,r.id,'measurement',e.target.value)} placeholder="Forma de medição"/></>}</EditableList></Section>
   <Section number="09" title="Providências prévias" text="Organize ações necessárias antes da contratação."><div className="preparation-list">{preparations.map(p=><div className="preparation-row" key={p.id}><input type="checkbox" checked={p.done} onChange={e=>update(preparations,setPreparations,p.id,'done',e.target.checked)}/><strong>{p.kind}</strong><input value={p.responsible} onChange={e=>update(preparations,setPreparations,p.id,'responsible',e.target.value)} placeholder="Responsável"/><input type="date" value={p.deadline} onChange={e=>update(preparations,setPreparations,p.id,'deadline',e.target.value)}/><input value={p.note} onChange={e=>update(preparations,setPreparations,p.id,'note',e.target.value)} placeholder="Observação"/></div>)}</div></Section>
   <Section number="10" title="Impactos e sustentabilidade" text="Considere impactos aplicáveis ao objeto."><label className="checkbox inline-check"><input type="checkbox" checked={data.sustainabilityNA} onChange={e=>change('sustainabilityNA',e.target.checked)}/><span><b>Não se aplica</b></span></label>{!data.sustainabilityNA&&<div className="form-grid"><Field wide label="Possíveis impactos ambientais"><textarea rows={3} value={data.environmentalImpact} onChange={e=>change('environmentalImpact',e.target.value)}/></Field><Field label="Medidas de mitigação"><textarea rows={3} value={data.mitigation} onChange={e=>change('mitigation',e.target.value)}/></Field><Field label="Requisitos de sustentabilidade"><textarea rows={3} value={data.sustainability} onChange={e=>change('sustainability',e.target.value)}/></Field></div>}</Section>
   <Section number="11" title="Conclusão de viabilidade" text="Consolide a conclusão técnica e econômica do estudo."><div className="form-grid"><Field label="A contratação é tecnicamente e economicamente viável?"><select required value={data.viable} onChange={e=>change('viable',e.target.value)}><option>Em análise</option><option>Sim</option><option>Não</option><option>Condicionada a providências</option></select></Field><Field label="Status"><select value={data.status} onChange={e=>change('status',e.target.value)}><option>Em elaboração</option><option>Pronto para revisão</option><option>Concluído</option></select></Field><Field wide label="Conclusão do ETP"><textarea rows={5} value={data.conclusion} onChange={e=>change('conclusion',e.target.value)}/></Field><Field label="Responsável pela elaboração"><input value={data.drafter} onChange={e=>change('drafter',e.target.value)} placeholder="Nome do responsável"/></Field></div></Section>
   <div className="form-actions dfd-actions"><button type="button" className="secondary" onClick={onBack}>Voltar para DFD</button><span/><button type="button" className="secondary" onClick={()=>setSaved(true)}>Salvar rascunho</button><button type="button" className="outline-primary" onClick={()=>change('status','Concluído')}>✓ Marcar ETP como concluído</button><button type="button" className="primary" onClick={onContinue}>Continuar para Riscos ›</button></div>
  </form></>
}

function EditableList<T extends {id:number}>({items,onRemove,onAdd,addLabel,children}:{items:T[];onRemove:(id:number)=>void;onAdd:()=>void;addLabel:string;children:(item:T)=>ReactNode}){return <><div className="generic-list">{items.map((item,i)=><div className="generic-row" key={item.id}><span className="row-number">{i+1}</span><div>{children(item)}</div><button type="button" onClick={()=>onRemove(item.id)}>×</button></div>)}</div><button type="button" className="add-button" onClick={onAdd}>＋ {addLabel}</button></>}
