import { useState, type ReactNode } from 'react'
import GovCopilot, { type CopilotItem } from './components/GovCopilot'

export type RiskItem={id:number;title:string;description:string;category:string;phase:string;probability:string;impact:string;responsible:string;note:string;preventive:string;contingency:string;actionOwner:string;deadline:string;status:string}
export type RiskMatrixData={notes:string;status:string}
export type RiskContext={object:string;secretariat:string;owner:string;estimatedValue:string;solution:string}
const steps=['Demanda','DFD','ETP','Riscos','Pesquisa de Preços','Termo de Referência','Aprovação']
const categories=['Planejamento','Técnico','Financeiro','Jurídico','Operacional','Fornecedor','Prazo','Segurança','Dados/LGPD','Outro']
const phases=['Planejamento','Seleção do fornecedor','Contratação','Implantação','Execução','Encerramento']

function Stepper(){return <div className="stepper">{steps.map((s,i)=><div className={`step ${i===3?'active':''} ${i<3?'done':''}`} key={s}><span>{i<3?'✓':i+1}</span><small>{s}</small></div>)}</div>}
function Section({number,title,text,children}:{number:string;title:string;text:string;children:ReactNode}){return <section className="form-section"><div className="section-title"><span>{number}</span><div><h2>{title}</h2><p>{text}</p></div></div>{children}</section>}
function Field({label,children,wide=false}:{label:string;children:ReactNode;wide?:boolean}){return <label className={`field ${wide?'wide':''}`}><span>{label}</span>{children}</label>}
export function riskLevel(probability:string,impact:string){const p={Baixa:1,Média:2,Alta:3}[probability]||1;const i={Baixo:1,Médio:2,Alto:3}[impact]||1;const score=p*i;return score>=9?'Crítico':score>=6?'Alto':score>=3?'Moderado':'Baixo'}

export default function RiskMatrix({context,data,setData,risks,setRisks,onBack,onContinue}:{context:RiskContext;data:RiskMatrixData;setData:(v:RiskMatrixData)=>void;risks:RiskItem[];setRisks:(v:RiskItem[])=>void;onBack:()=>void;onContinue:()=>void}){
 const [saved,setSaved]=useState(false);const change=(id:number,key:keyof RiskItem,value:string)=>setRisks(risks.map(r=>r.id===id?{...r,[key]:value}:r));const add=()=>setRisks([...risks,{id:Date.now(),title:'',description:'',category:'Planejamento',phase:'Planejamento',probability:'Baixa',impact:'Baixo',responsible:'',note:'',preventive:'',contingency:'',actionOwner:'',deadline:'',status:'Não iniciado'}])
 const high=risks.filter(r=>['Alto','Crítico'].includes(riskLevel(r.probability,r.impact))).length;const mitigated=risks.filter(r=>r.status==='Mitigado').length;const tracking=risks.filter(r=>r.status==='Em acompanhamento').length
 return <><header className="topbar"><div><span className="eyebrow">ETAPA 4 DE 7 · COMPRAS PÚBLICAS</span><h1>Matriz de Riscos</h1><p>Identifique os principais riscos da contratação e registre ações para prevenir ou tratar cada situação.</p></div></header><Stepper/><div className="stage-guidance"><div><strong>Você está na Matriz de Riscos</strong><span>Mapeie cada risco, avalie sua criticidade e defina como ele será tratado.</span></div><small>Você pode salvar e continuar depois.</small></div>
  <div className="process-context">{[['Objeto',context.object],['Secretaria',context.secretariat],['Responsável',context.owner],['Valor preliminar',context.estimatedValue],['Solução escolhida',context.solution]].map(([k,v])=><div key={k}><small>{k}</small><strong>{v||'Não informado'}</strong></div>)}</div>{saved&&<div className="toast">✓ Matriz salva localmente.</div>}
  <form className="panel form-panel" onSubmit={e=>e.preventDefault()}>
   <div className="copilot-toolbar"><strong>✨ Assistência disponível nesta etapa</strong><GovCopilot action="Sugerir riscos possíveis" context={[context.object,context.solution,context.estimatedValue]} suggestions={['DEMO — Três riscos foram identificados para avaliação individual.']} items={[{id:'integration',title:'DEMO — Falha na integração',reason:'A plataforma pode não trocar dados corretamente com sistemas existentes.',probability:'Média',impact:'Alto',prevention:'Validar integrações em ambiente de homologação.'},{id:'adoption',title:'DEMO — Baixa adesão dos usuários',reason:'Servidores e cidadãos podem ter dificuldade na mudança de canal.',probability:'Média',impact:'Médio',prevention:'Realizar capacitação e comunicação orientada.'},{id:'availability',title:'DEMO — Indisponibilidade do serviço',reason:'Interrupções podem impedir o registro e acompanhamento de solicitações.',probability:'Baixa',impact:'Alto',prevention:'Definir SLA, monitoramento e canal de contingência.'}]} onAddItem={(item:CopilotItem)=>setRisks([...risks,{id:Date.now(),title:item.title,description:item.reason,category:'Execução',phase:'Planejamento',probability:item.probability||'Média',impact:item.impact||'Médio',responsible:'',note:'Sugestão DEMO do Copiloto — revisar',preventive:item.prevention||'',contingency:'',actionOwner:'',deadline:'',status:'Não iniciado'}])}/></div>
   <Section number="01" title="Identificação dos riscos" text="Cadastre apenas situações que possam afetar o resultado da contratação."><div className="risk-cards">{risks.map((r,i)=><article className="risk-card" key={r.id}><div className="risk-card-head"><div><span>Risco {String(i+1).padStart(2,'0')}</span><strong className={`risk-level level-${riskLevel(r.probability,r.impact).toLowerCase()}`}>{riskLevel(r.probability,r.impact)}</strong></div><button type="button" onClick={()=>setRisks(risks.filter(x=>x.id!==r.id))}>Remover</button></div><div className="form-grid"><Field label="Título do risco"><input required value={r.title} onChange={e=>change(r.id,'title',e.target.value)} placeholder="Identifique o risco de forma objetiva"/></Field><Field label="Categoria"><select value={r.category} onChange={e=>change(r.id,'category',e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select></Field><Field wide label="Descrição"><textarea rows={3} value={r.description} onChange={e=>change(r.id,'description',e.target.value)} placeholder="Explique a situação e sua possível causa"/></Field><Field label="Fase"><select value={r.phase} onChange={e=>change(r.id,'phase',e.target.value)}>{phases.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Responsável"><input value={r.responsible} onChange={e=>change(r.id,'responsible',e.target.value)} placeholder="Responsável pelo acompanhamento"/></Field><Field label="Probabilidade"><select value={r.probability} onChange={e=>change(r.id,'probability',e.target.value)}><option>Baixa</option><option>Média</option><option>Alta</option></select></Field><Field label="Impacto"><select value={r.impact} onChange={e=>change(r.id,'impact',e.target.value)}><option>Baixo</option><option>Médio</option><option>Alto</option></select></Field><Field wide label="Observação"><input value={r.note} onChange={e=>change(r.id,'note',e.target.value)} placeholder="Informação complementar, se necessária"/></Field></div></article>)}</div><button type="button" className="add-button" onClick={add}>＋ Adicionar risco</button></Section>
   <Section number="02" title="Tratamento do risco" text="Defina prevenção e contingência para cada risco identificado.">{risks.length===0?<div className="empty-inline">Adicione um risco na seção anterior para definir seu tratamento.</div>:<div className="treatment-list">{risks.map((r,i)=><article key={r.id}><div className="treatment-title"><span>{i+1}</span><strong>{r.title||'Risco sem título'}</strong><em className={`risk-level level-${riskLevel(r.probability,r.impact).toLowerCase()}`}>{riskLevel(r.probability,r.impact)}</em></div><div className="form-grid"><Field label="Ação preventiva"><textarea rows={3} value={r.preventive} onChange={e=>change(r.id,'preventive',e.target.value)}/></Field><Field label="Ação de contingência"><textarea rows={3} value={r.contingency} onChange={e=>change(r.id,'contingency',e.target.value)}/></Field><Field label="Responsável pela ação"><input value={r.actionOwner} onChange={e=>change(r.id,'actionOwner',e.target.value)}/></Field><Field label="Prazo"><input type="date" value={r.deadline} onChange={e=>change(r.id,'deadline',e.target.value)}/></Field><Field label="Status"><select value={r.status} onChange={e=>change(r.id,'status',e.target.value)}><option>Não iniciado</option><option>Em acompanhamento</option><option>Mitigado</option><option>Ocorrido</option></select></Field></div></article>)}</div>}</Section>
   <Section number="03" title="Visão resumida" text="Acompanhe rapidamente a situação atual da matriz."><div className="risk-metrics">{[['Total de riscos',risks.length],['Riscos altos/críticos',high],['Riscos mitigados',mitigated],['Em acompanhamento',tracking]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><div className="table-wrap"><table className="risk-summary"><thead><tr>{['Risco','Probabilidade','Impacto','Nível','Responsável','Status'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{risks.map(r=><tr key={r.id}><td>{r.title||'Sem título'}</td><td>{r.probability}</td><td>{r.impact}</td><td><span className={`risk-level level-${riskLevel(r.probability,r.impact).toLowerCase()}`}>{riskLevel(r.probability,r.impact)}</span></td><td>{r.responsible||'—'}</td><td>{r.status}</td></tr>)}</tbody></table></div></Section>
   <Section number="04" title="Conclusão" text="Registre observações gerais e o estado de preparação da matriz."><div className="form-grid"><Field wide label="Observações gerais da matriz"><textarea rows={5} value={data.notes} onChange={e=>setData({...data,notes:e.target.value})}/></Field><Field label="Status"><select value={data.status} onChange={e=>setData({...data,status:e.target.value})}><option>Em elaboração</option><option>Pronta para revisão</option><option>Concluída</option></select></Field></div></Section>
   <div className="form-actions dfd-actions"><button type="button" className="secondary" onClick={onBack}>Voltar para ETP</button><span/><button type="button" className="secondary" onClick={()=>setSaved(true)}>Salvar rascunho</button><button type="button" className="outline-primary" onClick={()=>setData({...data,status:'Concluída'})}>✓ Marcar Matriz como concluída</button><button type="button" className="primary" onClick={onContinue}>Continuar para Pesquisa de Preços ›</button></div>
  </form></>
}
