import { useState } from 'react'
import type { Requirement, EtpData } from './Etp'
import type { RiskItem } from './RiskMatrix'
import type { PriceItem, PriceReference } from './PriceResearch'
import type { TrData } from './TermReference'
import GovCopilot from './components/GovCopilot'

export type ReviewStage='new-purchase'|'dfd'|'etp'|'risks'|'prices'|'tr'
type Severity='Informação'|'Atenção'|'Importante'|'Crítico'
export type ReviewIssue={id:string;type:string;stage:string;target:ReviewStage;section?:number;description:string;severity:Severity;suggestion:string}
export type ReviewContext={object:string;need:string;dfdNeed:string;solution:string;nature:string;etp:EtpData;requirements:Requirement[];risks:RiskItem[];priceItems:PriceItem[];references:PriceReference[];dfdItems:{id:number;description:string;quantity:string;unit:string}[];preliminaryValue:string;tr:TrData;continued:string;contractTerm:string;pca:boolean;pcaItem:string}
const sevOrder:Severity[]=['Crítico','Importante','Atenção','Informação'];const num=(v:string)=>Number(v.replace(/[^0-9,.-]/g,'').replace('.','').replace(',','.'))||0
function validValues(itemId:number,refs:PriceReference[]){return refs.filter(r=>r.itemId===itemId&&r.consider).map(r=>num(r.unitValue)).filter(n=>n>0).sort((a,b)=>a-b)}
function selected(item:PriceItem,refs:PriceReference[]){const v=validValues(item.id,refs);const avg=v.length?v.reduce((a,b)=>a+b,0)/v.length:0;const med=v.length?(v.length%2?v[(v.length-1)/2]:(v[v.length/2-1]+v[v.length/2])/2):0;return item.method==='Média'?avg:item.method==='Mediana'?med:item.method==='Menor preço'?(v[0]||0):num(item.customValue)}
const issue=(id:string,type:string,stage:string,target:ReviewStage,description:string,severity:Severity,suggestion:string,section?:number):ReviewIssue=>({id,type,stage,target,description,severity,suggestion,section})

export function runReview(c:ReviewContext):ReviewIssue[]{
 const total=c.priceItems.reduce((s,i)=>s+selected(i,c.references)*num(i.quantity),0);const preliminary=num(c.preliminaryValue);const high=c.risks.filter(r=>r.probability==='Alta'&&['Médio','Alto'].includes(r.impact));const checks:(ReviewIssue|null)[]=[
  c.object.trim().length<10?issue('object','Completude','Demanda','new-purchase','O objeto da contratação está ausente ou muito curto.','Importante','Descreva de forma objetiva o que será contratado.'):null,
  c.dfdNeed.trim().length>0&&c.need.trim().length===0?issue('need-etp','Coerência','ETP','etp','A necessidade foi informada no DFD, mas não aparece no contexto utilizado pelo ETP.','Importante','Revise a descrição da necessidade antes de concluir o estudo.',1):null,
  c.solution.trim().length>0&&c.tr.status!=='Em elaboração'&&c.solution.trim().length<3?issue('solution-tr','Coerência','Termo de Referência','tr','A solução escolhida no ETP não está refletida claramente no TR.','Importante','Revise a descrição da solução no Termo de Referência.',3):null,
  c.etp.viable==='Sim'&&c.etp.conclusion.trim().length<20?issue('viability','Justificativa','ETP','etp','O ETP indica que a contratação é viável, mas a conclusão ainda não explica o motivo.','Importante','Registre os fundamentos técnicos e econômicos da conclusão.',11):null,
  c.requirements.some(r=>r.title.trim())&&c.requirements.filter(r=>r.title.trim()).length===0?issue('requirements-tr','Coerência','Termo de Referência','tr','Existem requisitos no ETP que não aparecem no TR.','Importante','Revise os requisitos herdados pelo Termo de Referência.',4):null,
  /saas|software/i.test(`${c.nature} ${c.solution}`)&&!c.tr.hasSla?issue('sla','Configuração','Termo de Referência','tr','O ETP classificou a solução como software ou SaaS, porém o TR ainda não possui SLA configurado.','Importante','Defina disponibilidade, atendimento e indicadores mínimos de serviço.',6):null,
  high.some(r=>!r.preventive.trim())?issue('risk-preventive','Risco','Matriz de Riscos','risks','Há risco alto ou crítico sem ação preventiva.','Crítico','Defina uma ação para reduzir a chance de o risco ocorrer.',2):null,
  high.some(r=>!r.contingency.trim())?issue('risk-contingency','Risco','Matriz de Riscos','risks','Há risco alto ou crítico sem ação de contingência.','Crítico','Defina o que deverá ser feito caso o risco ocorra.',2):null,
  c.priceItems.some(i=>validValues(i.id,c.references).length<3)?issue('few-prices','Pesquisa de mercado','Pesquisa de Preços','prices','Um ou mais itens possuem menos de três referências válidas.','Atenção','Busque referências adicionais ou justifique a quantidade disponível.',2):null,
  c.references.some(r=>!r.consider&&(!r.reason.trim()||!r.justification.trim()))?issue('discard-reason','Rastreabilidade','Pesquisa de Preços','prices','Existe referência desconsiderada sem motivo e justificativa completos.','Importante','Registre por que o preço não representa adequadamente o mercado.',3):null,
  c.priceItems.some(i=>{const v=validValues(i.id,c.references);return v.length>1&&v.at(-1)!/v[0]>2})?issue('price-range','Consistência','Pesquisa de Preços','prices','Há diferença muito grande entre o menor e o maior preço de um item.','Atenção','Confira se as referências tratam do mesmo objeto e das mesmas condições.',5):null,
  preliminary>0&&total>0&&Math.abs(total-preliminary)/preliminary>.5?issue('price-preliminary','Consistência','Pesquisa de Preços','prices','O valor calculado na pesquisa está muito diferente do valor preliminar.','Atenção','Revise as referências e registre a razão da diferença.',6):null,
  c.dfdItems.some(d=>!c.priceItems.some(p=>p.id===d.id))?issue('dfd-price-item','Integridade','Pesquisa de Preços','prices','Existe item do DFD que não foi incluído na Pesquisa de Preços.','Crítico','Inclua todos os itens do escopo na pesquisa.',1):null,
  c.priceItems.some(p=>!c.dfdItems.some(d=>d.id===p.id))?issue('price-tr-item','Integridade','Termo de Referência','tr','Existe item da Pesquisa de Preços que não está relacionado ao escopo do TR.','Importante','Revise os itens e confirme o escopo final.',10):null,
  !c.tr.acceptance.trim()?issue('acceptance','Completude','Termo de Referência','tr','O Termo de Referência ainda não possui condição para aceite.','Importante','Defina como a Administração verificará se a entrega pode ser aceita.',8):null,
  !c.tr.deliveryDeadline.trim()?issue('delivery','Completude','Termo de Referência','tr','O prazo de implantação ou entrega ainda não foi informado.','Atenção','Informe um prazo estimado ou a regra que será utilizada.',5):null,
  !c.tr.monitoring.trim()?issue('inspection','Completude','Termo de Referência','tr','A forma de acompanhamento e fiscalização ainda não foi definida.','Importante','Explique como a execução será acompanhada.',7):null,
  c.continued==='Sim'&&!c.contractTerm.trim()?issue('continued-term','Completude','DFD','dfd','A contratação foi marcada como continuada, mas não possui prazo contratual estimado.','Importante','Informe o prazo inicial previsto para o contrato.',5):null,
  c.pca&&!c.pcaItem.trim()?issue('pca','Planejamento','Demanda','new-purchase','A contratação foi marcada como prevista no PCA, mas o item não foi identificado.','Atenção','Informe o número ou código do item no PCA.'):null,
  !c.object.trim()||!c.solution.trim()||!c.etp.drafter.trim()||!c.tr.drafter.trim()?issue('essential','Prontidão','Processo completo','tr','Ainda existem campos essenciais vazios antes da aprovação.','Crítico','Revise objeto, solução e responsáveis pela elaboração.',13):null,
 ];return checks.filter((x):x is ReviewIssue=>x!==null).sort((a,b)=>sevOrder.indexOf(a.severity)-sevOrder.indexOf(b.severity))
}

export default function SmartReview({context,reviewed,setReviewed,onBack,onCorrect}:{context:ReviewContext;reviewed:string[];setReviewed:(v:string[])=>void;onBack:()=>void;onCorrect:(target:ReviewStage,section?:number)=>void}){
 const issues=runReview(context);const [filter,setFilter]=useState('Todos');const filtered=issues.filter(i=>filter==='Todos'||filter==='Críticos'&&i.severity==='Crítico'||filter==='Importantes'&&i.severity==='Importante'||filter==='Atenção'&&i.severity==='Atenção'||filter==='Informações'&&i.severity==='Informação');const critical=issues.filter(i=>i.severity==='Crítico').length;const important=issues.filter(i=>i.severity==='Importante').length;const health=critical?'Crítica':important>=3?'Requer atenção':issues.length?'Boa':'Excelente'
 return <>
  <header className="topbar review-header"><div><span className="eyebrow">ASSISTÊNCIA AO SERVIDOR · REGRAS LOCAIS</span><h1>Revisão Inteligente do Processo</h1><p>Verificação orientativa das etapas de planejamento da contratação.</p></div><button className="secondary" onClick={onBack}>Fechar revisão</button></header>
  <div className="review-disclaimer">O GOV TOTAL auxilia na revisão, mas a análise e a decisão permanecem sob responsabilidade do servidor.</div>
  <section className="review-modes"><div><span>REGRAS AUTOMÁTICAS</span><strong>20 verificações objetivas</strong><small>Campos, valores, referências e requisitos verificáveis.</small></div><div><span>ANÁLISE ASSISTIDA POR IA · DEMO</span><strong>Coerência, clareza e possíveis lacunas contextuais</strong><small>Simulação orientativa; nenhuma API é chamada.</small><GovCopilot action="Fazer revisão aprofundada com IA" context={['Demanda, DFD e ETP','Matriz de Riscos','Pesquisa de Preços','Termo de Referência']} suggestions={['DEMO — O processo está coerente em seu objetivo central. Revise se os benefícios esperados possuem indicadores mensuráveis, detalhe a estratégia de adoção pelos usuários e confirme se o plano de contingência contempla indisponibilidade prolongada.']}/></div></section>
  <section className="review-summary"><div><small>Processo revisado</small><strong>6 etapas</strong></div><div><small>Verificações executadas</small><strong>20</strong></div><div><small>Pontos encontrados</small><strong>{issues.length}</strong></div><div><small>Críticos</small><strong>{critical}</strong></div><div><small>Importantes</small><strong>{important}</strong></div><div className={`health health-${health.toLowerCase().replace(' ','-')}`}><small>Saúde do processo</small><strong>{health}</strong></div></section>
  <nav className="review-filters">{['Todos','Críticos','Importantes','Atenção','Informações'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</nav>
  <div className="issue-list">{filtered.length===0?<div className="review-empty">Nenhum apontamento neste filtro.</div>:filtered.map(i=><article className={`issue-card severity-${i.severity.toLowerCase().replace('ç','c').replace('ã','a')}`} key={i.id}><div className="issue-main"><div className="issue-labels"><span>{i.severity}</span><small>{i.type}</small>{reviewed.includes(i.id)&&<em>Revisado</em>}</div><h2>{i.stage}</h2><p>{i.description}</p><div><strong>Sugestão</strong><span>{i.suggestion}</span></div></div><div className="issue-actions"><button className="primary" onClick={()=>onCorrect(i.target,i.section)}>Corrigir</button><button className="secondary" onClick={()=>setReviewed(reviewed.includes(i.id)?reviewed.filter(x=>x!==i.id):[...reviewed,i.id])}>{reviewed.includes(i.id)?'Remover marcação':'Marcar como revisado'}</button></div></article>)}</div>
 </>
}
