import { useEffect, useState, type ReactNode } from 'react'
import GovCopilot from './components/GovCopilot'
import type { PriceItem, PriceReference } from './PriceResearch'
import type { Requirement } from './Etp'
import type { RiskItem } from './RiskMatrix'

export type Milestone={id:number;name:string;deadline:string;deliverable:string;acceptance:string}
export type Sla={id:number;indicator:string;target:string;measurement:string;frequency:string;consequence:string}
export type TrData={startDeadline:string;deliveryDeadline:string;executionPlace:string;restrictions:string;supplierDuties:string;administrationDuties:string;hasSla:boolean;managementUnit:string;contractManager:string;technicalInspector:string;administrativeInspector:string;monitoring:string;evidence:string;inspectionFrequency:string;measurement:string;acceptance:string;paymentFrequency:string;paymentDeadline:string;requiredDocuments:string;paymentType:string;judgment:string;contractingMethod:string;minimumQualification:string;technicalQualification:string;certificates:string;responsibleSectorDefines:boolean;budget:string;fundingSource:string;budgetProgram:string;budgetUndefined:boolean;drafter:string;department:string;finalNotes:string;status:string}
export type TrContext={secretariat:string;owner:string;object:string;solution:string;solutionDescription:string;nature:string;need:string;problem:string;justification:string;results:string;viabilityConclusion:string;sustainability:string;items:{id:number;description:string;quantity:string;unit:string;note:string}[];requirements:Requirement[];risks:RiskItem[];priceItems:PriceItem[];references:PriceReference[];methodologyReason:string}
const steps=['Demanda','DFD','ETP','Riscos','Pesquisa de Preços','Termo de Referência','Aprovação']
const money=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});const num=(v:string)=>Number(v.replace(/[^0-9,.-]/g,'').replace('.','').replace(',','.'))||0
function price(item:PriceItem,refs:PriceReference[]){const vals=refs.filter(r=>r.itemId===item.id&&r.consider).map(r=>num(r.unitValue)).filter(Boolean).sort((a,b)=>a-b);const avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0;const med=vals.length?(vals.length%2?vals[(vals.length-1)/2]:(vals[vals.length/2-1]+vals[vals.length/2])/2):0;const unit=item.method==='Média'?avg:item.method==='Mediana'?med:item.method==='Menor preço'?(vals[0]||0):num(item.customValue);return{unit,total:unit*num(item.quantity)}}
function Stepper(){return <div className="stepper">{steps.map((s,i)=><div className={`step ${i===5?'active':''} ${i<5?'done':''}`} key={s}><span>{i<5?'✓':i+1}</span><small>{s}</small></div>)}</div>}
function Field({label,children,wide=false}:{label:string;children:ReactNode;wide?:boolean}){return <label className={`field ${wide?'wide':''}`}><span>{label}</span>{children}</label>}
const sections=[['01','Objeto da contratação'],['02','Fundamentação da contratação'],['03','Descrição da solução'],['04','Requisitos da contratação'],['05','Modelo de execução'],['06','Níveis de serviço / SLA'],['07','Gestão e fiscalização'],['08','Medição e pagamento'],['09','Seleção do fornecedor'],['10','Estimativa da contratação'],['11','Adequação orçamentária'],['12','Riscos e controles'],['13','Responsáveis e conclusão']]

export default function TermReference({focusSection,context,data,setData,milestones,setMilestones,slas,setSlas,requirements,setRequirements,onBack,onRisks,onContinue}:{focusSection?:number;context:TrContext;data:TrData;setData:(v:TrData)=>void;milestones:Milestone[];setMilestones:(v:Milestone[])=>void;slas:Sla[];setSlas:(v:Sla[])=>void;requirements:Requirement[];setRequirements:(v:Requirement[])=>void;onBack:()=>void;onRisks:()=>void;onContinue:()=>void}){
 const [open,setOpen]=useState<number[]>([1,2]);const [saved,setSaved]=useState(false);const change=(k:keyof TrData,v:string|boolean)=>setData({...data,[k]:v});const toggle=(n:number)=>setOpen(open.includes(n)?open.filter(x=>x!==n):[...open,n]);const complete=[context.object,context.solution,data.executionPlace,data.measurement,data.judgment,data.drafter].filter(Boolean).length;const progress=Math.round(complete/6*100);const total=context.priceItems.reduce((s,i)=>s+price(i,context.references).total,0);const high=context.risks.filter(r=>['Alta'].includes(r.probability)&&['Alto','Médio'].includes(r.impact)).length
 const updateMilestone=(id:number,k:keyof Milestone,v:string)=>setMilestones(milestones.map(x=>x.id===id?{...x,[k]:v}:x));const updateSla=(id:number,k:keyof Sla,v:string)=>setSlas(slas.map(x=>x.id===id?{...x,[k]:v}:x));const updateReq=(id:number,k:keyof Requirement,v:string)=>setRequirements(requirements.map(x=>x.id===id?{...x,[k]:v}:x))
 useEffect(()=>{if(focusSection){setOpen(current=>current.includes(focusSection)?current:[...current,focusSection]);setTimeout(()=>document.getElementById(`tr-${focusSection}`)?.scrollIntoView({behavior:'smooth'}),80)}},[focusSection])
 return <><header className="topbar"><div><span className="eyebrow">ETAPA 6 DE 7 · COMPRAS PÚBLICAS</span><h1>TR — Termo de Referência</h1><p>Documento que detalha o que será contratado, os requisitos, as responsabilidades e as condições para execução e fiscalização.</p></div></header><Stepper/><div className="stage-guidance"><div><strong>Você está construindo o Termo de Referência</strong><span>Grande parte do TR já está estruturada com informações das etapas anteriores.</span></div><small>Você pode salvar e continuar depois.</small></div>
  <div className="tr-overview"><div className="tr-progress"><div><strong>{progress}%</strong><span>estrutura preenchida</span></div><i><b style={{width:`${progress}%`}}/></i></div>{[['Status',data.status],['Secretaria',context.secretariat],['Responsável',context.owner],['Objeto',context.object],['Valor estimado',money(total)]].map(([k,v])=><div key={k}><small>{k}</small><strong>{v||'Não informado'}</strong></div>)}</div><div className="inherit-banner">✓ Informações aproveitadas das etapas anteriores</div>{saved&&<div className="toast">✓ Termo de Referência salvo localmente.</div>}
  <div className="tr-layout"><nav className="tr-nav">{sections.map(([n,t],i)=><button type="button" className={open.includes(i+1)?'active':''} onClick={()=>{if(!open.includes(i+1))setOpen([...open,i+1]);document.getElementById(`tr-${i+1}`)?.scrollIntoView({behavior:'smooth'})}} key={n}><span>{n}</span>{t}</button>)}</nav><form className="tr-form" onSubmit={e=>e.preventDefault()}>
   <div className="copilot-toolbar tr-copilot"><strong>✨ Preparação assistida do TR</strong><div><GovCopilot action="Preparar modelo de execução" context={['Necessidade do DFD','Solução do ETP',`${context.requirements.length} requisitos`,`Valor estimado: ${money(total)}`,`${context.risks.length} riscos`]} value={data.supplierDuties} onChange={value=>change('supplierDuties',value)} suggestions={['DEMO — A contratada deverá implantar a solução conforme cronograma aprovado, configurar perfis e integrações, capacitar os usuários e manter suporte técnico durante a vigência, com entregas verificadas pela fiscalização.']}/><GovCopilot action="Preparar fiscalização" context={['Necessidade do DFD','Solução do ETP','Requisitos','Valor estimado','Riscos da contratação']} value={data.monitoring} onChange={value=>change('monitoring',value)} suggestions={['DEMO — A execução será acompanhada pelo gestor e pelos fiscais designados mediante reuniões de acompanhamento, relatórios mensais, evidências de atendimento e verificação dos indicadores de serviço.']}/></div></div>
   <TrSection n={1} title="Objeto da contratação" hint="Dados herdados da Demanda, do DFD e do ETP." open={open.includes(1)} toggle={toggle}><div className="form-grid inherited-grid"><Field wide label="Objeto"><textarea rows={3} value={context.object} readOnly/></Field><Field label="Natureza da solução"><input value={context.nature} readOnly/></Field><Field wide label="Descrição da solução"><textarea rows={4} value={context.solutionDescription} readOnly/></Field></div><InheritedItems items={context.items}/></TrSection>
   <TrSection n={2} title="Fundamentação da contratação" hint="Síntese organizada do DFD e do ETP, sem repetir informações." open={open.includes(2)} toggle={toggle}><div className="form-grid inherited-grid"><Field wide label="Necessidade"><textarea rows={3} value={context.need} readOnly/></Field><Field wide label="Problema a resolver"><textarea rows={3} value={context.problem} readOnly/></Field><Field wide label="Justificativa"><textarea rows={3} value={context.justification} readOnly/></Field><Field wide label="Resultados pretendidos"><textarea rows={3} value={context.results} readOnly/></Field><Field wide label="Conclusão de viabilidade"><textarea rows={3} value={context.viabilityConclusion} readOnly/></Field></div></TrSection>
   <TrSection n={3} title="Descrição da solução" hint="Solução escolhida e aspectos avaliados no ETP." open={open.includes(3)} toggle={toggle}><div className="form-grid inherited-grid"><Field label="Solução escolhida"><input value={context.solution} readOnly/></Field><Field wide label="Descrição"><textarea rows={4} value={context.solutionDescription} readOnly/></Field></div><div className="solution-tags">{['Integração','Implantação','Suporte','Segurança','Acessibilidade','Sustentabilidade'].map(type=>{const matches=context.requirements.filter(r=>r.type.toLowerCase().includes(type.toLowerCase()));return <div key={type}><strong>{type}</strong><span>{matches.map(x=>x.title).filter(Boolean).join(', ')|| (type==='Sustentabilidade'&&context.sustainability)||'Não especificado'}</span></div>})}</div></TrSection>
   <TrSection n={4} title="Requisitos da contratação" hint="Requisitos herdados do ETP; você pode refiná-los aqui." open={open.includes(4)} toggle={toggle}><div className="tr-requirements">{requirements.map((r,i)=><div key={r.id}><span>{i+1}</span><input value={r.title} onChange={e=>updateReq(r.id,'title',e.target.value)} placeholder="Título"/><select value={r.type} onChange={e=>updateReq(r.id,'type',e.target.value)}><option>Funcional</option><option>Técnico</option><option>Segurança</option><option>Implantação</option><option>Suporte</option><option>Acessibilidade</option><option>Sustentabilidade</option><option>Outro</option></select><textarea value={r.description} onChange={e=>updateReq(r.id,'description',e.target.value)} placeholder="Descrição"/><button type="button" onClick={()=>setRequirements(requirements.filter(x=>x.id!==r.id))}>×</button></div>)}</div><button type="button" className="add-button" onClick={()=>setRequirements([...requirements,{id:Date.now(),title:'',description:'',type:'Funcional'}])}>＋ Adicionar requisito</button></TrSection>
   <TrSection n={5} title="Modelo de execução" hint="Defina como a solução deverá ser entregue e aceita." open={open.includes(5)} toggle={toggle}><div className="form-grid"><Field label="Prazo para início"><input value={data.startDeadline} onChange={e=>change('startDeadline',e.target.value)}/></Field><Field label="Prazo de implantação/entrega"><input value={data.deliveryDeadline} onChange={e=>change('deliveryDeadline',e.target.value)}/></Field><Field wide label="Local ou forma de execução"><input value={data.executionPlace} onChange={e=>change('executionPlace',e.target.value)}/></Field><Field wide label="Horários/restrições, quando aplicável"><input value={data.restrictions} onChange={e=>change('restrictions',e.target.value)}/></Field><Field label="Obrigações da contratada"><textarea rows={5} value={data.supplierDuties} onChange={e=>change('supplierDuties',e.target.value)}/></Field><Field label="Obrigações da Administração"><textarea rows={5} value={data.administrationDuties} onChange={e=>change('administrationDuties',e.target.value)}/></Field></div><h3 className="subheading">Etapas e marcos da execução</h3><MiniRows items={milestones} remove={id=>setMilestones(milestones.filter(x=>x.id!==id))}>{m=><><input value={m.name} onChange={e=>updateMilestone(m.id,'name',e.target.value)} placeholder="Marco"/><input value={m.deadline} onChange={e=>updateMilestone(m.id,'deadline',e.target.value)} placeholder="Prazo"/><input value={m.deliverable} onChange={e=>updateMilestone(m.id,'deliverable',e.target.value)} placeholder="Entregável"/><input value={m.acceptance} onChange={e=>updateMilestone(m.id,'acceptance',e.target.value)} placeholder="Critério de aceite"/></>}</MiniRows><button type="button" className="add-button" onClick={()=>setMilestones([...milestones,{id:Date.now(),name:'',deadline:'',deliverable:'',acceptance:''}])}>＋ Adicionar marco</button></TrSection>
   <TrSection n={6} title="Níveis de serviço / SLA" hint="Use somente quando forem necessários níveis mínimos mensuráveis." open={open.includes(6)} toggle={toggle}><label className="checkbox inline-check"><input type="checkbox" checked={data.hasSla} onChange={e=>change('hasSla',e.target.checked)}/><span><b>Esta contratação necessita níveis mínimos de serviço</b></span></label>{data.hasSla&&<><MiniRows items={slas} remove={id=>setSlas(slas.filter(x=>x.id!==id))}>{s=><><input value={s.indicator} onChange={e=>updateSla(s.id,'indicator',e.target.value)} placeholder="Indicador"/><input value={s.target} onChange={e=>updateSla(s.id,'target',e.target.value)} placeholder="Meta"/><input value={s.measurement} onChange={e=>updateSla(s.id,'measurement',e.target.value)} placeholder="Forma de medição"/><input value={s.frequency} onChange={e=>updateSla(s.id,'frequency',e.target.value)} placeholder="Periodicidade"/><input value={s.consequence} onChange={e=>updateSla(s.id,'consequence',e.target.value)} placeholder="Consequência"/></>}</MiniRows><button type="button" className="add-button" onClick={()=>setSlas([...slas,{id:Date.now(),indicator:'',target:'',measurement:'',frequency:'',consequence:''}])}>＋ Adicionar nível de serviço</button></>}</TrSection>
   <TrSection n={7} title="Gestão e fiscalização" hint="Os nomes definitivos podem ser informados posteriormente." open={open.includes(7)} toggle={toggle}><div className="form-grid"><Field label="Unidade responsável"><input value={data.managementUnit} onChange={e=>change('managementUnit',e.target.value)}/></Field><Field label="Gestor do contrato"><input value={data.contractManager} onChange={e=>change('contractManager',e.target.value)} placeholder="Pode ser definido posteriormente"/></Field><Field label="Fiscal técnico"><input value={data.technicalInspector} onChange={e=>change('technicalInspector',e.target.value)}/></Field><Field label="Fiscal administrativo, quando aplicável"><input value={data.administrativeInspector} onChange={e=>change('administrativeInspector',e.target.value)}/></Field><Field wide label="Forma de acompanhamento"><textarea rows={3} value={data.monitoring} onChange={e=>change('monitoring',e.target.value)}/></Field><Field label="Evidências/relatórios esperados"><textarea rows={3} value={data.evidence} onChange={e=>change('evidence',e.target.value)}/></Field><Field label="Periodicidade da fiscalização"><input value={data.inspectionFrequency} onChange={e=>change('inspectionFrequency',e.target.value)}/></Field></div></TrSection>
   <TrSection n={8} title="Critérios de medição e pagamento" hint="Defina como entregas serão verificadas e pagas." open={open.includes(8)} toggle={toggle}><div className="form-grid"><Field label="Forma de medição"><textarea rows={3} value={data.measurement} onChange={e=>change('measurement',e.target.value)}/></Field><Field label="Condição para aceite"><textarea rows={3} value={data.acceptance} onChange={e=>change('acceptance',e.target.value)}/></Field><Field label="Pagamento"><select value={data.paymentType} onChange={e=>change('paymentType',e.target.value)}><option>Único</option><option>Mensal</option><option>Por etapa</option><option>Por entrega</option><option>Outro</option></select></Field><Field label="Periodicidade de pagamento"><input value={data.paymentFrequency} onChange={e=>change('paymentFrequency',e.target.value)}/></Field><Field label="Prazo previsto para pagamento"><input value={data.paymentDeadline} onChange={e=>change('paymentDeadline',e.target.value)}/></Field><Field label="Documentos necessários"><textarea rows={3} value={data.requiredDocuments} onChange={e=>change('requiredDocuments',e.target.value)}/></Field></div></TrSection>
   <TrSection n={9} title="Seleção do fornecedor" hint="Não inclua exigências jurídicas que ainda não tenham sido definidas." open={open.includes(9)} toggle={toggle}><label className="checkbox inline-check"><input type="checkbox" checked={data.responsibleSectorDefines} onChange={e=>change('responsibleSectorDefines',e.target.checked)}/><span><b>A definir pelo setor responsável</b></span></label>{!data.responsibleSectorDefines&&<div className="form-grid"><Field label="Critério de julgamento"><input value={data.judgment} onChange={e=>change('judgment',e.target.value)}/></Field><Field label="Forma de contratação"><input value={data.contractingMethod} onChange={e=>change('contractingMethod',e.target.value)}/></Field><Field wide label="Requisitos mínimos de habilitação"><textarea rows={3} value={data.minimumQualification} onChange={e=>change('minimumQualification',e.target.value)}/></Field><Field label="Qualificação técnica necessária"><textarea rows={3} value={data.technicalQualification} onChange={e=>change('technicalQualification',e.target.value)}/></Field><Field label="Atestados/capacidade técnica, quando aplicável"><textarea rows={3} value={data.certificates} onChange={e=>change('certificates',e.target.value)}/></Field></div>}</TrSection>
   <TrSection n={10} title="Estimativa da contratação" hint="Origem: Pesquisa de Preços. Nenhuma redigitação necessária." open={open.includes(10)} toggle={toggle}><div className="origin-label">Origem: Pesquisa de Preços</div><div className="table-wrap"><table><thead><tr><th>Item</th><th>Quantidade</th><th>Valor unitário estimado</th><th>Total</th><th>Metodologia</th></tr></thead><tbody>{context.priceItems.map(i=>{const p=price(i,context.references);return <tr key={i.id}><td>{i.description}</td><td>{i.quantity} {i.unit}</td><td>{money(p.unit)}</td><td><strong>{money(p.total)}</strong></td><td>{i.method}</td></tr>})}</tbody></table></div><div className="tr-total"><span>Valor total estimado</span><strong>{money(total)}</strong></div>{context.methodologyReason&&<p className="methodology-note"><b>Justificativa da metodologia:</b> {context.methodologyReason}</p>}</TrSection>
   <TrSection n={11} title="Adequação orçamentária" hint="Não bloqueia a conclusão quando ainda não estiver disponível." open={open.includes(11)} toggle={toggle}><label className="checkbox inline-check"><input type="checkbox" checked={data.budgetUndefined} onChange={e=>change('budgetUndefined',e.target.checked)}/><span><b>A definir</b></span></label>{!data.budgetUndefined&&<div className="form-grid"><Field label="Dotação"><input value={data.budget} onChange={e=>change('budget',e.target.value)}/></Field><Field label="Fonte"><input value={data.fundingSource} onChange={e=>change('fundingSource',e.target.value)}/></Field><Field wide label="Programa/Ação"><input value={data.budgetProgram} onChange={e=>change('budgetProgram',e.target.value)}/></Field></div>}</TrSection>
   <TrSection n={12} title="Riscos e controles" hint="Resumo da Matriz de Riscos, sem duplicar seu conteúdo." open={open.includes(12)} toggle={toggle}><div className="risk-metrics"><div><span>Quantidade de riscos</span><strong>{context.risks.length}</strong></div><div><span>Riscos altos/críticos</span><strong>{high}</strong></div><div><span>Principais controles</span><strong>{context.risks.filter(r=>r.preventive).length}</strong></div></div><div className="controls-summary">{context.risks.filter(r=>r.preventive).slice(0,3).map(r=><div key={r.id}><strong>{r.title}</strong><span>{r.preventive}</span></div>)}</div><button type="button" className="secondary" onClick={onRisks}>Ver Matriz de Riscos</button></TrSection>
   <TrSection n={13} title="Responsáveis e conclusão" hint="Finalize a preparação do TR para revisão." open={open.includes(13)} toggle={toggle}><div className="form-grid"><Field label="Responsável pela elaboração"><input value={data.drafter} onChange={e=>change('drafter',e.target.value)}/></Field><Field label="Setor"><input value={data.department} onChange={e=>change('department',e.target.value)}/></Field><Field wide label="Observações finais"><textarea rows={5} value={data.finalNotes} onChange={e=>change('finalNotes',e.target.value)}/></Field><Field label="Status"><select value={data.status} onChange={e=>change('status',e.target.value)}><option>Em elaboração</option><option>Pronto para revisão</option><option>Concluído</option></select></Field></div></TrSection>
   <div className="form-actions dfd-actions tr-actions"><button type="button" className="secondary" onClick={onBack}>Voltar para Pesquisa de Preços</button><span/><button type="button" className="secondary" onClick={()=>setSaved(true)}>Salvar rascunho</button><button type="button" className="outline-primary" onClick={()=>change('status','Concluído')}>✓ Marcar TR como concluído</button><button type="button" className="primary" onClick={onContinue}>Continuar para Aprovação ›</button></div>
  </form></div></>
}

function TrSection({n,title,hint,open,toggle,children}:{n:number;title:string;hint:string;open:boolean;toggle:(n:number)=>void;children:ReactNode}){return <section className={`tr-section ${open?'open':''}`} id={`tr-${n}`}><button type="button" className="tr-section-head" onClick={()=>toggle(n)}><span>{String(n).padStart(2,'0')}</span><div><strong>{title}</strong><small>{hint}</small></div><b>{open?'−':'+'}</b></button>{open&&<div className="tr-section-body">{children}</div>}</section>}
function InheritedItems({items}:{items:TrContext['items']}){return <div className="inherited-scope"><strong>Itens, quantidades e unidades</strong>{items.map((x,i)=><div key={x.id}><span>{i+1}</span><p>{x.description||'Item sem descrição'}</p><b>{x.quantity} {x.unit}</b></div>)}</div>}
function MiniRows<T extends{id:number}>({items,remove,children}:{items:T[];remove:(id:number)=>void;children:(x:T)=>ReactNode}){return <div className="mini-rows">{items.map((x,i)=><div key={x.id}><span>{i+1}</span><div>{children(x)}</div><button type="button" onClick={()=>remove(x.id)}>×</button></div>)}</div>}
